// Code generated by counterfeiter. DO NOT EDIT.
package servicesfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/services"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/vm"
)

type FakeNetworkService struct {
	ConfigureNetworkStub        func(string, vm.NetworkConfig) error
	configureNetworkMutex       sync.RWMutex
	configureNetworkArgsForCall []struct {
		arg1 string
		arg2 vm.NetworkConfig
	}
	configureNetworkReturns struct {
		result1 error
	}
	configureNetworkReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNetworkService) ConfigureNetwork(arg1 string, arg2 vm.NetworkConfig) error {
	fake.configureNetworkMutex.Lock()
	ret, specificReturn := fake.configureNetworkReturnsOnCall[len(fake.configureNetworkArgsForCall)]
	fake.configureNetworkArgsForCall = append(fake.configureNetworkArgsForCall, struct {
		arg1 string
		arg2 vm.NetworkConfig
	}{arg1, arg2})
	stub := fake.ConfigureNetworkStub
	fakeReturns := fake.configureNetworkReturns
	fake.recordInvocation("ConfigureNetwork", []interface{}{arg1, arg2})
	fake.configureNetworkMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkService) ConfigureNetworkCallCount() int {
	fake.configureNetworkMutex.RLock()
	defer fake.configureNetworkMutex.RUnlock()
	return len(fake.configureNetworkArgsForCall)
}

func (fake *FakeNetworkService) ConfigureNetworkCalls(stub func(string, vm.NetworkConfig) error) {
	fake.configureNetworkMutex.Lock()
	defer fake.configureNetworkMutex.Unlock()
	fake.ConfigureNetworkStub = stub
}

func (fake *FakeNetworkService) ConfigureNetworkArgsForCall(i int) (string, vm.NetworkConfig) {
	fake.configureNetworkMutex.RLock()
	defer fake.configureNetworkMutex.RUnlock()
	argsForCall := fake.configureNetworkArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNetworkService) ConfigureNetworkReturns(result1 error) {
	fake.configureNetworkMutex.Lock()
	defer fake.configureNetworkMutex.Unlock()
	fake.ConfigureNetworkStub = nil
	fake.configureNetworkReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNetworkService) ConfigureNetworkReturnsOnCall(i int, result1 error) {
	fake.configureNetworkMutex.Lock()
	defer fake.configureNetworkMutex.Unlock()
	fake.ConfigureNetworkStub = nil
	if fake.configureNetworkReturnsOnCall == nil {
		fake.configureNetworkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.configureNetworkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNetworkService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.configureNetworkMutex.RLock()
	defer fake.configureNetworkMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNetworkService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.NetworkService = new(FakeNetworkService)
