// Code generated by counterfeiter. DO NOT EDIT.
package servicesfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/services"
)

type FakeServiceFactory struct {
	CreateImageServiceStub        func() (services.ImageService, error)
	createImageServiceMutex       sync.RWMutex
	createImageServiceArgsForCall []struct {
	}
	createImageServiceReturns struct {
		result1 services.ImageService
		result2 error
	}
	createImageServiceReturnsOnCall map[int]struct {
		result1 services.ImageService
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServiceFactory) CreateImageService() (services.ImageService, error) {
	fake.createImageServiceMutex.Lock()
	ret, specificReturn := fake.createImageServiceReturnsOnCall[len(fake.createImageServiceArgsForCall)]
	fake.createImageServiceArgsForCall = append(fake.createImageServiceArgsForCall, struct {
	}{})
	stub := fake.CreateImageServiceStub
	fakeReturns := fake.createImageServiceReturns
	fake.recordInvocation("CreateImageService", []interface{}{})
	fake.createImageServiceMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeServiceFactory) CreateImageServiceCallCount() int {
	fake.createImageServiceMutex.RLock()
	defer fake.createImageServiceMutex.RUnlock()
	return len(fake.createImageServiceArgsForCall)
}

func (fake *FakeServiceFactory) CreateImageServiceCalls(stub func() (services.ImageService, error)) {
	fake.createImageServiceMutex.Lock()
	defer fake.createImageServiceMutex.Unlock()
	fake.CreateImageServiceStub = stub
}

func (fake *FakeServiceFactory) CreateImageServiceReturns(result1 services.ImageService, result2 error) {
	fake.createImageServiceMutex.Lock()
	defer fake.createImageServiceMutex.Unlock()
	fake.CreateImageServiceStub = nil
	fake.createImageServiceReturns = struct {
		result1 services.ImageService
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceFactory) CreateImageServiceReturnsOnCall(i int, result1 services.ImageService, result2 error) {
	fake.createImageServiceMutex.Lock()
	defer fake.createImageServiceMutex.Unlock()
	fake.CreateImageServiceStub = nil
	if fake.createImageServiceReturnsOnCall == nil {
		fake.createImageServiceReturnsOnCall = make(map[int]struct {
			result1 services.ImageService
			result2 error
		})
	}
	fake.createImageServiceReturnsOnCall[i] = struct {
		result1 services.ImageService
		result2 error
	}{result1, result2}
}

func (fake *FakeServiceFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createImageServiceMutex.RLock()
	defer fake.createImageServiceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServiceFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.ServiceFactory = new(FakeServiceFactory)
