// Code generated by counterfeiter. DO NOT EDIT.
package facadesfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/services/facades"
	"github.com/gophercloud/gophercloud"
)

type FakeOpenstackFacade struct {
	AuthenticatedClientStub        func(gophercloud.AuthOptions) (*gophercloud.ProviderClient, error)
	authenticatedClientMutex       sync.RWMutex
	authenticatedClientArgsForCall []struct {
		arg1 gophercloud.AuthOptions
	}
	authenticatedClientReturns struct {
		result1 *gophercloud.ProviderClient
		result2 error
	}
	authenticatedClientReturnsOnCall map[int]struct {
		result1 *gophercloud.ProviderClient
		result2 error
	}
	NewImageServiceV2Stub        func(*gophercloud.ProviderClient, gophercloud.EndpointOpts) (*gophercloud.ServiceClient, error)
	newImageServiceV2Mutex       sync.RWMutex
	newImageServiceV2ArgsForCall []struct {
		arg1 *gophercloud.ProviderClient
		arg2 gophercloud.EndpointOpts
	}
	newImageServiceV2Returns struct {
		result1 *gophercloud.ServiceClient
		result2 error
	}
	newImageServiceV2ReturnsOnCall map[int]struct {
		result1 *gophercloud.ServiceClient
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeOpenstackFacade) AuthenticatedClient(arg1 gophercloud.AuthOptions) (*gophercloud.ProviderClient, error) {
	fake.authenticatedClientMutex.Lock()
	ret, specificReturn := fake.authenticatedClientReturnsOnCall[len(fake.authenticatedClientArgsForCall)]
	fake.authenticatedClientArgsForCall = append(fake.authenticatedClientArgsForCall, struct {
		arg1 gophercloud.AuthOptions
	}{arg1})
	stub := fake.AuthenticatedClientStub
	fakeReturns := fake.authenticatedClientReturns
	fake.recordInvocation("AuthenticatedClient", []interface{}{arg1})
	fake.authenticatedClientMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOpenstackFacade) AuthenticatedClientCallCount() int {
	fake.authenticatedClientMutex.RLock()
	defer fake.authenticatedClientMutex.RUnlock()
	return len(fake.authenticatedClientArgsForCall)
}

func (fake *FakeOpenstackFacade) AuthenticatedClientCalls(stub func(gophercloud.AuthOptions) (*gophercloud.ProviderClient, error)) {
	fake.authenticatedClientMutex.Lock()
	defer fake.authenticatedClientMutex.Unlock()
	fake.AuthenticatedClientStub = stub
}

func (fake *FakeOpenstackFacade) AuthenticatedClientArgsForCall(i int) gophercloud.AuthOptions {
	fake.authenticatedClientMutex.RLock()
	defer fake.authenticatedClientMutex.RUnlock()
	argsForCall := fake.authenticatedClientArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeOpenstackFacade) AuthenticatedClientReturns(result1 *gophercloud.ProviderClient, result2 error) {
	fake.authenticatedClientMutex.Lock()
	defer fake.authenticatedClientMutex.Unlock()
	fake.AuthenticatedClientStub = nil
	fake.authenticatedClientReturns = struct {
		result1 *gophercloud.ProviderClient
		result2 error
	}{result1, result2}
}

func (fake *FakeOpenstackFacade) AuthenticatedClientReturnsOnCall(i int, result1 *gophercloud.ProviderClient, result2 error) {
	fake.authenticatedClientMutex.Lock()
	defer fake.authenticatedClientMutex.Unlock()
	fake.AuthenticatedClientStub = nil
	if fake.authenticatedClientReturnsOnCall == nil {
		fake.authenticatedClientReturnsOnCall = make(map[int]struct {
			result1 *gophercloud.ProviderClient
			result2 error
		})
	}
	fake.authenticatedClientReturnsOnCall[i] = struct {
		result1 *gophercloud.ProviderClient
		result2 error
	}{result1, result2}
}

func (fake *FakeOpenstackFacade) NewImageServiceV2(arg1 *gophercloud.ProviderClient, arg2 gophercloud.EndpointOpts) (*gophercloud.ServiceClient, error) {
	fake.newImageServiceV2Mutex.Lock()
	ret, specificReturn := fake.newImageServiceV2ReturnsOnCall[len(fake.newImageServiceV2ArgsForCall)]
	fake.newImageServiceV2ArgsForCall = append(fake.newImageServiceV2ArgsForCall, struct {
		arg1 *gophercloud.ProviderClient
		arg2 gophercloud.EndpointOpts
	}{arg1, arg2})
	stub := fake.NewImageServiceV2Stub
	fakeReturns := fake.newImageServiceV2Returns
	fake.recordInvocation("NewImageServiceV2", []interface{}{arg1, arg2})
	fake.newImageServiceV2Mutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeOpenstackFacade) NewImageServiceV2CallCount() int {
	fake.newImageServiceV2Mutex.RLock()
	defer fake.newImageServiceV2Mutex.RUnlock()
	return len(fake.newImageServiceV2ArgsForCall)
}

func (fake *FakeOpenstackFacade) NewImageServiceV2Calls(stub func(*gophercloud.ProviderClient, gophercloud.EndpointOpts) (*gophercloud.ServiceClient, error)) {
	fake.newImageServiceV2Mutex.Lock()
	defer fake.newImageServiceV2Mutex.Unlock()
	fake.NewImageServiceV2Stub = stub
}

func (fake *FakeOpenstackFacade) NewImageServiceV2ArgsForCall(i int) (*gophercloud.ProviderClient, gophercloud.EndpointOpts) {
	fake.newImageServiceV2Mutex.RLock()
	defer fake.newImageServiceV2Mutex.RUnlock()
	argsForCall := fake.newImageServiceV2ArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeOpenstackFacade) NewImageServiceV2Returns(result1 *gophercloud.ServiceClient, result2 error) {
	fake.newImageServiceV2Mutex.Lock()
	defer fake.newImageServiceV2Mutex.Unlock()
	fake.NewImageServiceV2Stub = nil
	fake.newImageServiceV2Returns = struct {
		result1 *gophercloud.ServiceClient
		result2 error
	}{result1, result2}
}

func (fake *FakeOpenstackFacade) NewImageServiceV2ReturnsOnCall(i int, result1 *gophercloud.ServiceClient, result2 error) {
	fake.newImageServiceV2Mutex.Lock()
	defer fake.newImageServiceV2Mutex.Unlock()
	fake.NewImageServiceV2Stub = nil
	if fake.newImageServiceV2ReturnsOnCall == nil {
		fake.newImageServiceV2ReturnsOnCall = make(map[int]struct {
			result1 *gophercloud.ServiceClient
			result2 error
		})
	}
	fake.newImageServiceV2ReturnsOnCall[i] = struct {
		result1 *gophercloud.ServiceClient
		result2 error
	}{result1, result2}
}

func (fake *FakeOpenstackFacade) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.authenticatedClientMutex.RLock()
	defer fake.authenticatedClientMutex.RUnlock()
	fake.newImageServiceV2Mutex.RLock()
	defer fake.newImageServiceV2Mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeOpenstackFacade) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ facades.OpenstackFacade = new(FakeOpenstackFacade)
