// Code generated by counterfeiter. DO NOT EDIT.
package computefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/compute"
	"github.com/gophercloud/gophercloud"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/keypairs"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/flavors"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
	"github.com/gophercloud/gophercloud/pagination"
)

type FakeComputeFacade struct {
	CreateServerStub        func(*gophercloud.ServiceClient, servers.CreateOptsBuilder) (*servers.Server, error)
	createServerMutex       sync.RWMutex
	createServerArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 servers.CreateOptsBuilder
	}
	createServerReturns struct {
		result1 *servers.Server
		result2 error
	}
	createServerReturnsOnCall map[int]struct {
		result1 *servers.Server
		result2 error
	}
	DeleteServerStub        func(*gophercloud.ServiceClient, string) error
	deleteServerMutex       sync.RWMutex
	deleteServerArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
	}
	deleteServerReturns struct {
		result1 error
	}
	deleteServerReturnsOnCall map[int]struct {
		result1 error
	}
	ExtractFlavorsStub        func(pagination.Page) ([]flavors.Flavor, error)
	extractFlavorsMutex       sync.RWMutex
	extractFlavorsArgsForCall []struct {
		arg1 pagination.Page
	}
	extractFlavorsReturns struct {
		result1 []flavors.Flavor
		result2 error
	}
	extractFlavorsReturnsOnCall map[int]struct {
		result1 []flavors.Flavor
		result2 error
	}
	GetOSKeyPairStub        func(*gophercloud.ServiceClient, string, keypairs.GetOpts) (*keypairs.KeyPair, error)
	getOSKeyPairMutex       sync.RWMutex
	getOSKeyPairArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
		arg3 keypairs.GetOpts
	}
	getOSKeyPairReturns struct {
		result1 *keypairs.KeyPair
		result2 error
	}
	getOSKeyPairReturnsOnCall map[int]struct {
		result1 *keypairs.KeyPair
		result2 error
	}
	GetServerStub        func(*gophercloud.ServiceClient, string) (*servers.Server, error)
	getServerMutex       sync.RWMutex
	getServerArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
	}
	getServerReturns struct {
		result1 *servers.Server
		result2 error
	}
	getServerReturnsOnCall map[int]struct {
		result1 *servers.Server
		result2 error
	}
	GetServerTagsStub        func(*gophercloud.ServiceClient, string) ([]string, error)
	getServerTagsMutex       sync.RWMutex
	getServerTagsArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
	}
	getServerTagsReturns struct {
		result1 []string
		result2 error
	}
	getServerTagsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	ListFlavorsStub        func(*gophercloud.ServiceClient, flavors.ListOpts) (pagination.Page, error)
	listFlavorsMutex       sync.RWMutex
	listFlavorsArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 flavors.ListOpts
	}
	listFlavorsReturns struct {
		result1 pagination.Page
		result2 error
	}
	listFlavorsReturnsOnCall map[int]struct {
		result1 pagination.Page
		result2 error
	}
	SetServerMetadataStub        func(*gophercloud.ServiceClient, string, servers.MetadatumOpts) (map[string]string, error)
	setServerMetadataMutex       sync.RWMutex
	setServerMetadataArgsForCall []struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
		arg3 servers.MetadatumOpts
	}
	setServerMetadataReturns struct {
		result1 map[string]string
		result2 error
	}
	setServerMetadataReturnsOnCall map[int]struct {
		result1 map[string]string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeComputeFacade) CreateServer(arg1 *gophercloud.ServiceClient, arg2 servers.CreateOptsBuilder) (*servers.Server, error) {
	fake.createServerMutex.Lock()
	ret, specificReturn := fake.createServerReturnsOnCall[len(fake.createServerArgsForCall)]
	fake.createServerArgsForCall = append(fake.createServerArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 servers.CreateOptsBuilder
	}{arg1, arg2})
	stub := fake.CreateServerStub
	fakeReturns := fake.createServerReturns
	fake.recordInvocation("CreateServer", []interface{}{arg1, arg2})
	fake.createServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) CreateServerCallCount() int {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	return len(fake.createServerArgsForCall)
}

func (fake *FakeComputeFacade) CreateServerCalls(stub func(*gophercloud.ServiceClient, servers.CreateOptsBuilder) (*servers.Server, error)) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = stub
}

func (fake *FakeComputeFacade) CreateServerArgsForCall(i int) (*gophercloud.ServiceClient, servers.CreateOptsBuilder) {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	argsForCall := fake.createServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeFacade) CreateServerReturns(result1 *servers.Server, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	fake.createServerReturns = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) CreateServerReturnsOnCall(i int, result1 *servers.Server, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	if fake.createServerReturnsOnCall == nil {
		fake.createServerReturnsOnCall = make(map[int]struct {
			result1 *servers.Server
			result2 error
		})
	}
	fake.createServerReturnsOnCall[i] = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) DeleteServer(arg1 *gophercloud.ServiceClient, arg2 string) error {
	fake.deleteServerMutex.Lock()
	ret, specificReturn := fake.deleteServerReturnsOnCall[len(fake.deleteServerArgsForCall)]
	fake.deleteServerArgsForCall = append(fake.deleteServerArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
	}{arg1, arg2})
	stub := fake.DeleteServerStub
	fakeReturns := fake.deleteServerReturns
	fake.recordInvocation("DeleteServer", []interface{}{arg1, arg2})
	fake.deleteServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeComputeFacade) DeleteServerCallCount() int {
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	return len(fake.deleteServerArgsForCall)
}

func (fake *FakeComputeFacade) DeleteServerCalls(stub func(*gophercloud.ServiceClient, string) error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = stub
}

func (fake *FakeComputeFacade) DeleteServerArgsForCall(i int) (*gophercloud.ServiceClient, string) {
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	argsForCall := fake.deleteServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeFacade) DeleteServerReturns(result1 error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = nil
	fake.deleteServerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeFacade) DeleteServerReturnsOnCall(i int, result1 error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = nil
	if fake.deleteServerReturnsOnCall == nil {
		fake.deleteServerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeFacade) ExtractFlavors(arg1 pagination.Page) ([]flavors.Flavor, error) {
	fake.extractFlavorsMutex.Lock()
	ret, specificReturn := fake.extractFlavorsReturnsOnCall[len(fake.extractFlavorsArgsForCall)]
	fake.extractFlavorsArgsForCall = append(fake.extractFlavorsArgsForCall, struct {
		arg1 pagination.Page
	}{arg1})
	stub := fake.ExtractFlavorsStub
	fakeReturns := fake.extractFlavorsReturns
	fake.recordInvocation("ExtractFlavors", []interface{}{arg1})
	fake.extractFlavorsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) ExtractFlavorsCallCount() int {
	fake.extractFlavorsMutex.RLock()
	defer fake.extractFlavorsMutex.RUnlock()
	return len(fake.extractFlavorsArgsForCall)
}

func (fake *FakeComputeFacade) ExtractFlavorsCalls(stub func(pagination.Page) ([]flavors.Flavor, error)) {
	fake.extractFlavorsMutex.Lock()
	defer fake.extractFlavorsMutex.Unlock()
	fake.ExtractFlavorsStub = stub
}

func (fake *FakeComputeFacade) ExtractFlavorsArgsForCall(i int) pagination.Page {
	fake.extractFlavorsMutex.RLock()
	defer fake.extractFlavorsMutex.RUnlock()
	argsForCall := fake.extractFlavorsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeComputeFacade) ExtractFlavorsReturns(result1 []flavors.Flavor, result2 error) {
	fake.extractFlavorsMutex.Lock()
	defer fake.extractFlavorsMutex.Unlock()
	fake.ExtractFlavorsStub = nil
	fake.extractFlavorsReturns = struct {
		result1 []flavors.Flavor
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) ExtractFlavorsReturnsOnCall(i int, result1 []flavors.Flavor, result2 error) {
	fake.extractFlavorsMutex.Lock()
	defer fake.extractFlavorsMutex.Unlock()
	fake.ExtractFlavorsStub = nil
	if fake.extractFlavorsReturnsOnCall == nil {
		fake.extractFlavorsReturnsOnCall = make(map[int]struct {
			result1 []flavors.Flavor
			result2 error
		})
	}
	fake.extractFlavorsReturnsOnCall[i] = struct {
		result1 []flavors.Flavor
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) GetOSKeyPair(arg1 *gophercloud.ServiceClient, arg2 string, arg3 keypairs.GetOpts) (*keypairs.KeyPair, error) {
	fake.getOSKeyPairMutex.Lock()
	ret, specificReturn := fake.getOSKeyPairReturnsOnCall[len(fake.getOSKeyPairArgsForCall)]
	fake.getOSKeyPairArgsForCall = append(fake.getOSKeyPairArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
		arg3 keypairs.GetOpts
	}{arg1, arg2, arg3})
	stub := fake.GetOSKeyPairStub
	fakeReturns := fake.getOSKeyPairReturns
	fake.recordInvocation("GetOSKeyPair", []interface{}{arg1, arg2, arg3})
	fake.getOSKeyPairMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) GetOSKeyPairCallCount() int {
	fake.getOSKeyPairMutex.RLock()
	defer fake.getOSKeyPairMutex.RUnlock()
	return len(fake.getOSKeyPairArgsForCall)
}

func (fake *FakeComputeFacade) GetOSKeyPairCalls(stub func(*gophercloud.ServiceClient, string, keypairs.GetOpts) (*keypairs.KeyPair, error)) {
	fake.getOSKeyPairMutex.Lock()
	defer fake.getOSKeyPairMutex.Unlock()
	fake.GetOSKeyPairStub = stub
}

func (fake *FakeComputeFacade) GetOSKeyPairArgsForCall(i int) (*gophercloud.ServiceClient, string, keypairs.GetOpts) {
	fake.getOSKeyPairMutex.RLock()
	defer fake.getOSKeyPairMutex.RUnlock()
	argsForCall := fake.getOSKeyPairArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeComputeFacade) GetOSKeyPairReturns(result1 *keypairs.KeyPair, result2 error) {
	fake.getOSKeyPairMutex.Lock()
	defer fake.getOSKeyPairMutex.Unlock()
	fake.GetOSKeyPairStub = nil
	fake.getOSKeyPairReturns = struct {
		result1 *keypairs.KeyPair
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) GetOSKeyPairReturnsOnCall(i int, result1 *keypairs.KeyPair, result2 error) {
	fake.getOSKeyPairMutex.Lock()
	defer fake.getOSKeyPairMutex.Unlock()
	fake.GetOSKeyPairStub = nil
	if fake.getOSKeyPairReturnsOnCall == nil {
		fake.getOSKeyPairReturnsOnCall = make(map[int]struct {
			result1 *keypairs.KeyPair
			result2 error
		})
	}
	fake.getOSKeyPairReturnsOnCall[i] = struct {
		result1 *keypairs.KeyPair
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) GetServer(arg1 *gophercloud.ServiceClient, arg2 string) (*servers.Server, error) {
	fake.getServerMutex.Lock()
	ret, specificReturn := fake.getServerReturnsOnCall[len(fake.getServerArgsForCall)]
	fake.getServerArgsForCall = append(fake.getServerArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
	}{arg1, arg2})
	stub := fake.GetServerStub
	fakeReturns := fake.getServerReturns
	fake.recordInvocation("GetServer", []interface{}{arg1, arg2})
	fake.getServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) GetServerCallCount() int {
	fake.getServerMutex.RLock()
	defer fake.getServerMutex.RUnlock()
	return len(fake.getServerArgsForCall)
}

func (fake *FakeComputeFacade) GetServerCalls(stub func(*gophercloud.ServiceClient, string) (*servers.Server, error)) {
	fake.getServerMutex.Lock()
	defer fake.getServerMutex.Unlock()
	fake.GetServerStub = stub
}

func (fake *FakeComputeFacade) GetServerArgsForCall(i int) (*gophercloud.ServiceClient, string) {
	fake.getServerMutex.RLock()
	defer fake.getServerMutex.RUnlock()
	argsForCall := fake.getServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeFacade) GetServerReturns(result1 *servers.Server, result2 error) {
	fake.getServerMutex.Lock()
	defer fake.getServerMutex.Unlock()
	fake.GetServerStub = nil
	fake.getServerReturns = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) GetServerReturnsOnCall(i int, result1 *servers.Server, result2 error) {
	fake.getServerMutex.Lock()
	defer fake.getServerMutex.Unlock()
	fake.GetServerStub = nil
	if fake.getServerReturnsOnCall == nil {
		fake.getServerReturnsOnCall = make(map[int]struct {
			result1 *servers.Server
			result2 error
		})
	}
	fake.getServerReturnsOnCall[i] = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) GetServerTags(arg1 *gophercloud.ServiceClient, arg2 string) ([]string, error) {
	fake.getServerTagsMutex.Lock()
	ret, specificReturn := fake.getServerTagsReturnsOnCall[len(fake.getServerTagsArgsForCall)]
	fake.getServerTagsArgsForCall = append(fake.getServerTagsArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
	}{arg1, arg2})
	stub := fake.GetServerTagsStub
	fakeReturns := fake.getServerTagsReturns
	fake.recordInvocation("GetServerTags", []interface{}{arg1, arg2})
	fake.getServerTagsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) GetServerTagsCallCount() int {
	fake.getServerTagsMutex.RLock()
	defer fake.getServerTagsMutex.RUnlock()
	return len(fake.getServerTagsArgsForCall)
}

func (fake *FakeComputeFacade) GetServerTagsCalls(stub func(*gophercloud.ServiceClient, string) ([]string, error)) {
	fake.getServerTagsMutex.Lock()
	defer fake.getServerTagsMutex.Unlock()
	fake.GetServerTagsStub = stub
}

func (fake *FakeComputeFacade) GetServerTagsArgsForCall(i int) (*gophercloud.ServiceClient, string) {
	fake.getServerTagsMutex.RLock()
	defer fake.getServerTagsMutex.RUnlock()
	argsForCall := fake.getServerTagsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeFacade) GetServerTagsReturns(result1 []string, result2 error) {
	fake.getServerTagsMutex.Lock()
	defer fake.getServerTagsMutex.Unlock()
	fake.GetServerTagsStub = nil
	fake.getServerTagsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) GetServerTagsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getServerTagsMutex.Lock()
	defer fake.getServerTagsMutex.Unlock()
	fake.GetServerTagsStub = nil
	if fake.getServerTagsReturnsOnCall == nil {
		fake.getServerTagsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getServerTagsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) ListFlavors(arg1 *gophercloud.ServiceClient, arg2 flavors.ListOpts) (pagination.Page, error) {
	fake.listFlavorsMutex.Lock()
	ret, specificReturn := fake.listFlavorsReturnsOnCall[len(fake.listFlavorsArgsForCall)]
	fake.listFlavorsArgsForCall = append(fake.listFlavorsArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 flavors.ListOpts
	}{arg1, arg2})
	stub := fake.ListFlavorsStub
	fakeReturns := fake.listFlavorsReturns
	fake.recordInvocation("ListFlavors", []interface{}{arg1, arg2})
	fake.listFlavorsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) ListFlavorsCallCount() int {
	fake.listFlavorsMutex.RLock()
	defer fake.listFlavorsMutex.RUnlock()
	return len(fake.listFlavorsArgsForCall)
}

func (fake *FakeComputeFacade) ListFlavorsCalls(stub func(*gophercloud.ServiceClient, flavors.ListOpts) (pagination.Page, error)) {
	fake.listFlavorsMutex.Lock()
	defer fake.listFlavorsMutex.Unlock()
	fake.ListFlavorsStub = stub
}

func (fake *FakeComputeFacade) ListFlavorsArgsForCall(i int) (*gophercloud.ServiceClient, flavors.ListOpts) {
	fake.listFlavorsMutex.RLock()
	defer fake.listFlavorsMutex.RUnlock()
	argsForCall := fake.listFlavorsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeFacade) ListFlavorsReturns(result1 pagination.Page, result2 error) {
	fake.listFlavorsMutex.Lock()
	defer fake.listFlavorsMutex.Unlock()
	fake.ListFlavorsStub = nil
	fake.listFlavorsReturns = struct {
		result1 pagination.Page
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) ListFlavorsReturnsOnCall(i int, result1 pagination.Page, result2 error) {
	fake.listFlavorsMutex.Lock()
	defer fake.listFlavorsMutex.Unlock()
	fake.ListFlavorsStub = nil
	if fake.listFlavorsReturnsOnCall == nil {
		fake.listFlavorsReturnsOnCall = make(map[int]struct {
			result1 pagination.Page
			result2 error
		})
	}
	fake.listFlavorsReturnsOnCall[i] = struct {
		result1 pagination.Page
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) SetServerMetadata(arg1 *gophercloud.ServiceClient, arg2 string, arg3 servers.MetadatumOpts) (map[string]string, error) {
	fake.setServerMetadataMutex.Lock()
	ret, specificReturn := fake.setServerMetadataReturnsOnCall[len(fake.setServerMetadataArgsForCall)]
	fake.setServerMetadataArgsForCall = append(fake.setServerMetadataArgsForCall, struct {
		arg1 *gophercloud.ServiceClient
		arg2 string
		arg3 servers.MetadatumOpts
	}{arg1, arg2, arg3})
	stub := fake.SetServerMetadataStub
	fakeReturns := fake.setServerMetadataReturns
	fake.recordInvocation("SetServerMetadata", []interface{}{arg1, arg2, arg3})
	fake.setServerMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeFacade) SetServerMetadataCallCount() int {
	fake.setServerMetadataMutex.RLock()
	defer fake.setServerMetadataMutex.RUnlock()
	return len(fake.setServerMetadataArgsForCall)
}

func (fake *FakeComputeFacade) SetServerMetadataCalls(stub func(*gophercloud.ServiceClient, string, servers.MetadatumOpts) (map[string]string, error)) {
	fake.setServerMetadataMutex.Lock()
	defer fake.setServerMetadataMutex.Unlock()
	fake.SetServerMetadataStub = stub
}

func (fake *FakeComputeFacade) SetServerMetadataArgsForCall(i int) (*gophercloud.ServiceClient, string, servers.MetadatumOpts) {
	fake.setServerMetadataMutex.RLock()
	defer fake.setServerMetadataMutex.RUnlock()
	argsForCall := fake.setServerMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeComputeFacade) SetServerMetadataReturns(result1 map[string]string, result2 error) {
	fake.setServerMetadataMutex.Lock()
	defer fake.setServerMetadataMutex.Unlock()
	fake.SetServerMetadataStub = nil
	fake.setServerMetadataReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) SetServerMetadataReturnsOnCall(i int, result1 map[string]string, result2 error) {
	fake.setServerMetadataMutex.Lock()
	defer fake.setServerMetadataMutex.Unlock()
	fake.SetServerMetadataStub = nil
	if fake.setServerMetadataReturnsOnCall == nil {
		fake.setServerMetadataReturnsOnCall = make(map[int]struct {
			result1 map[string]string
			result2 error
		})
	}
	fake.setServerMetadataReturnsOnCall[i] = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeFacade) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	fake.extractFlavorsMutex.RLock()
	defer fake.extractFlavorsMutex.RUnlock()
	fake.getOSKeyPairMutex.RLock()
	defer fake.getOSKeyPairMutex.RUnlock()
	fake.getServerMutex.RLock()
	defer fake.getServerMutex.RUnlock()
	fake.getServerTagsMutex.RLock()
	defer fake.getServerTagsMutex.RUnlock()
	fake.listFlavorsMutex.RLock()
	defer fake.listFlavorsMutex.RUnlock()
	fake.setServerMetadataMutex.RLock()
	defer fake.setServerMetadataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeComputeFacade) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ compute.ComputeFacade = new(FakeComputeFacade)
