// Code generated by counterfeiter. DO NOT EDIT.
package computefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cpi-go/apiv1"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/compute"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/config"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/flavors"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
)

type FakeComputeService struct {
	CreateServerStub        func(apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, apiv1.AgentID, apiv1.VMEnv, config.CpiConfig) (*servers.Server, error)
	createServerMutex       sync.RWMutex
	createServerArgsForCall []struct {
		arg1 apiv1.StemcellCID
		arg2 properties.CreateVM
		arg3 properties.NetworkConfig
		arg4 apiv1.AgentID
		arg5 apiv1.VMEnv
		arg6 config.CpiConfig
	}
	createServerReturns struct {
		result1 *servers.Server
		result2 error
	}
	createServerReturnsOnCall map[int]struct {
		result1 *servers.Server
		result2 error
	}
	DeleteServerStub        func(string, config.CpiConfig) error
	deleteServerMutex       sync.RWMutex
	deleteServerArgsForCall []struct {
		arg1 string
		arg2 config.CpiConfig
	}
	deleteServerReturns struct {
		result1 error
	}
	deleteServerReturnsOnCall map[int]struct {
		result1 error
	}
	GetMatchingFlavorStub        func(apiv1.VMResources, bool) (flavors.Flavor, error)
	getMatchingFlavorMutex       sync.RWMutex
	getMatchingFlavorArgsForCall []struct {
		arg1 apiv1.VMResources
		arg2 bool
	}
	getMatchingFlavorReturns struct {
		result1 flavors.Flavor
		result2 error
	}
	getMatchingFlavorReturnsOnCall map[int]struct {
		result1 flavors.Flavor
		result2 error
	}
	GetMetadataStub        func(string) (map[string]string, error)
	getMetadataMutex       sync.RWMutex
	getMetadataArgsForCall []struct {
		arg1 string
	}
	getMetadataReturns struct {
		result1 map[string]string
		result2 error
	}
	getMetadataReturnsOnCall map[int]struct {
		result1 map[string]string
		result2 error
	}
	GetServerStub        func(string) (*servers.Server, error)
	getServerMutex       sync.RWMutex
	getServerArgsForCall []struct {
		arg1 string
	}
	getServerReturns struct {
		result1 *servers.Server
		result2 error
	}
	getServerReturnsOnCall map[int]struct {
		result1 *servers.Server
		result2 error
	}
	RebootServerStub        func(string, config.CpiConfig) error
	rebootServerMutex       sync.RWMutex
	rebootServerArgsForCall []struct {
		arg1 string
		arg2 config.CpiConfig
	}
	rebootServerReturns struct {
		result1 error
	}
	rebootServerReturnsOnCall map[int]struct {
		result1 error
	}
	SetMetadataStub        func(servers.Server, properties.ServerTags) error
	setMetadataMutex       sync.RWMutex
	setMetadataArgsForCall []struct {
		arg1 servers.Server
		arg2 properties.ServerTags
	}
	setMetadataReturns struct {
		result1 error
	}
	setMetadataReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeComputeService) CreateServer(arg1 apiv1.StemcellCID, arg2 properties.CreateVM, arg3 properties.NetworkConfig, arg4 apiv1.AgentID, arg5 apiv1.VMEnv, arg6 config.CpiConfig) (*servers.Server, error) {
	fake.createServerMutex.Lock()
	ret, specificReturn := fake.createServerReturnsOnCall[len(fake.createServerArgsForCall)]
	fake.createServerArgsForCall = append(fake.createServerArgsForCall, struct {
		arg1 apiv1.StemcellCID
		arg2 properties.CreateVM
		arg3 properties.NetworkConfig
		arg4 apiv1.AgentID
		arg5 apiv1.VMEnv
		arg6 config.CpiConfig
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CreateServerStub
	fakeReturns := fake.createServerReturns
	fake.recordInvocation("CreateServer", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.createServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeService) CreateServerCallCount() int {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	return len(fake.createServerArgsForCall)
}

func (fake *FakeComputeService) CreateServerCalls(stub func(apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, apiv1.AgentID, apiv1.VMEnv, config.CpiConfig) (*servers.Server, error)) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = stub
}

func (fake *FakeComputeService) CreateServerArgsForCall(i int) (apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, apiv1.AgentID, apiv1.VMEnv, config.CpiConfig) {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	argsForCall := fake.createServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeComputeService) CreateServerReturns(result1 *servers.Server, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	fake.createServerReturns = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) CreateServerReturnsOnCall(i int, result1 *servers.Server, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	if fake.createServerReturnsOnCall == nil {
		fake.createServerReturnsOnCall = make(map[int]struct {
			result1 *servers.Server
			result2 error
		})
	}
	fake.createServerReturnsOnCall[i] = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) DeleteServer(arg1 string, arg2 config.CpiConfig) error {
	fake.deleteServerMutex.Lock()
	ret, specificReturn := fake.deleteServerReturnsOnCall[len(fake.deleteServerArgsForCall)]
	fake.deleteServerArgsForCall = append(fake.deleteServerArgsForCall, struct {
		arg1 string
		arg2 config.CpiConfig
	}{arg1, arg2})
	stub := fake.DeleteServerStub
	fakeReturns := fake.deleteServerReturns
	fake.recordInvocation("DeleteServer", []interface{}{arg1, arg2})
	fake.deleteServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeComputeService) DeleteServerCallCount() int {
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	return len(fake.deleteServerArgsForCall)
}

func (fake *FakeComputeService) DeleteServerCalls(stub func(string, config.CpiConfig) error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = stub
}

func (fake *FakeComputeService) DeleteServerArgsForCall(i int) (string, config.CpiConfig) {
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	argsForCall := fake.deleteServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeService) DeleteServerReturns(result1 error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = nil
	fake.deleteServerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) DeleteServerReturnsOnCall(i int, result1 error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = nil
	if fake.deleteServerReturnsOnCall == nil {
		fake.deleteServerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) GetMatchingFlavor(arg1 apiv1.VMResources, arg2 bool) (flavors.Flavor, error) {
	fake.getMatchingFlavorMutex.Lock()
	ret, specificReturn := fake.getMatchingFlavorReturnsOnCall[len(fake.getMatchingFlavorArgsForCall)]
	fake.getMatchingFlavorArgsForCall = append(fake.getMatchingFlavorArgsForCall, struct {
		arg1 apiv1.VMResources
		arg2 bool
	}{arg1, arg2})
	stub := fake.GetMatchingFlavorStub
	fakeReturns := fake.getMatchingFlavorReturns
	fake.recordInvocation("GetMatchingFlavor", []interface{}{arg1, arg2})
	fake.getMatchingFlavorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeService) GetMatchingFlavorCallCount() int {
	fake.getMatchingFlavorMutex.RLock()
	defer fake.getMatchingFlavorMutex.RUnlock()
	return len(fake.getMatchingFlavorArgsForCall)
}

func (fake *FakeComputeService) GetMatchingFlavorCalls(stub func(apiv1.VMResources, bool) (flavors.Flavor, error)) {
	fake.getMatchingFlavorMutex.Lock()
	defer fake.getMatchingFlavorMutex.Unlock()
	fake.GetMatchingFlavorStub = stub
}

func (fake *FakeComputeService) GetMatchingFlavorArgsForCall(i int) (apiv1.VMResources, bool) {
	fake.getMatchingFlavorMutex.RLock()
	defer fake.getMatchingFlavorMutex.RUnlock()
	argsForCall := fake.getMatchingFlavorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeService) GetMatchingFlavorReturns(result1 flavors.Flavor, result2 error) {
	fake.getMatchingFlavorMutex.Lock()
	defer fake.getMatchingFlavorMutex.Unlock()
	fake.GetMatchingFlavorStub = nil
	fake.getMatchingFlavorReturns = struct {
		result1 flavors.Flavor
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) GetMatchingFlavorReturnsOnCall(i int, result1 flavors.Flavor, result2 error) {
	fake.getMatchingFlavorMutex.Lock()
	defer fake.getMatchingFlavorMutex.Unlock()
	fake.GetMatchingFlavorStub = nil
	if fake.getMatchingFlavorReturnsOnCall == nil {
		fake.getMatchingFlavorReturnsOnCall = make(map[int]struct {
			result1 flavors.Flavor
			result2 error
		})
	}
	fake.getMatchingFlavorReturnsOnCall[i] = struct {
		result1 flavors.Flavor
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) GetMetadata(arg1 string) (map[string]string, error) {
	fake.getMetadataMutex.Lock()
	ret, specificReturn := fake.getMetadataReturnsOnCall[len(fake.getMetadataArgsForCall)]
	fake.getMetadataArgsForCall = append(fake.getMetadataArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetMetadataStub
	fakeReturns := fake.getMetadataReturns
	fake.recordInvocation("GetMetadata", []interface{}{arg1})
	fake.getMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeService) GetMetadataCallCount() int {
	fake.getMetadataMutex.RLock()
	defer fake.getMetadataMutex.RUnlock()
	return len(fake.getMetadataArgsForCall)
}

func (fake *FakeComputeService) GetMetadataCalls(stub func(string) (map[string]string, error)) {
	fake.getMetadataMutex.Lock()
	defer fake.getMetadataMutex.Unlock()
	fake.GetMetadataStub = stub
}

func (fake *FakeComputeService) GetMetadataArgsForCall(i int) string {
	fake.getMetadataMutex.RLock()
	defer fake.getMetadataMutex.RUnlock()
	argsForCall := fake.getMetadataArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeComputeService) GetMetadataReturns(result1 map[string]string, result2 error) {
	fake.getMetadataMutex.Lock()
	defer fake.getMetadataMutex.Unlock()
	fake.GetMetadataStub = nil
	fake.getMetadataReturns = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) GetMetadataReturnsOnCall(i int, result1 map[string]string, result2 error) {
	fake.getMetadataMutex.Lock()
	defer fake.getMetadataMutex.Unlock()
	fake.GetMetadataStub = nil
	if fake.getMetadataReturnsOnCall == nil {
		fake.getMetadataReturnsOnCall = make(map[int]struct {
			result1 map[string]string
			result2 error
		})
	}
	fake.getMetadataReturnsOnCall[i] = struct {
		result1 map[string]string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) GetServer(arg1 string) (*servers.Server, error) {
	fake.getServerMutex.Lock()
	ret, specificReturn := fake.getServerReturnsOnCall[len(fake.getServerArgsForCall)]
	fake.getServerArgsForCall = append(fake.getServerArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetServerStub
	fakeReturns := fake.getServerReturns
	fake.recordInvocation("GetServer", []interface{}{arg1})
	fake.getServerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeService) GetServerCallCount() int {
	fake.getServerMutex.RLock()
	defer fake.getServerMutex.RUnlock()
	return len(fake.getServerArgsForCall)
}

func (fake *FakeComputeService) GetServerCalls(stub func(string) (*servers.Server, error)) {
	fake.getServerMutex.Lock()
	defer fake.getServerMutex.Unlock()
	fake.GetServerStub = stub
}

func (fake *FakeComputeService) GetServerArgsForCall(i int) string {
	fake.getServerMutex.RLock()
	defer fake.getServerMutex.RUnlock()
	argsForCall := fake.getServerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeComputeService) GetServerReturns(result1 *servers.Server, result2 error) {
	fake.getServerMutex.Lock()
	defer fake.getServerMutex.Unlock()
	fake.GetServerStub = nil
	fake.getServerReturns = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) GetServerReturnsOnCall(i int, result1 *servers.Server, result2 error) {
	fake.getServerMutex.Lock()
	defer fake.getServerMutex.Unlock()
	fake.GetServerStub = nil
	if fake.getServerReturnsOnCall == nil {
		fake.getServerReturnsOnCall = make(map[int]struct {
			result1 *servers.Server
			result2 error
		})
	}
	fake.getServerReturnsOnCall[i] = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) RebootServer(arg1 string, arg2 config.CpiConfig) error {
	fake.rebootServerMutex.Lock()
	ret, specificReturn := fake.rebootServerReturnsOnCall[len(fake.rebootServerArgsForCall)]
	fake.rebootServerArgsForCall = append(fake.rebootServerArgsForCall, struct {
		arg1 string
		arg2 config.CpiConfig
	}{arg1, arg2})
	stub := fake.RebootServerStub
	fakeReturns := fake.rebootServerReturns
	fake.recordInvocation("RebootServer", []interface{}{arg1, arg2})
	fake.rebootServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeComputeService) RebootServerCallCount() int {
	fake.rebootServerMutex.RLock()
	defer fake.rebootServerMutex.RUnlock()
	return len(fake.rebootServerArgsForCall)
}

func (fake *FakeComputeService) RebootServerCalls(stub func(string, config.CpiConfig) error) {
	fake.rebootServerMutex.Lock()
	defer fake.rebootServerMutex.Unlock()
	fake.RebootServerStub = stub
}

func (fake *FakeComputeService) RebootServerArgsForCall(i int) (string, config.CpiConfig) {
	fake.rebootServerMutex.RLock()
	defer fake.rebootServerMutex.RUnlock()
	argsForCall := fake.rebootServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeService) RebootServerReturns(result1 error) {
	fake.rebootServerMutex.Lock()
	defer fake.rebootServerMutex.Unlock()
	fake.RebootServerStub = nil
	fake.rebootServerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) RebootServerReturnsOnCall(i int, result1 error) {
	fake.rebootServerMutex.Lock()
	defer fake.rebootServerMutex.Unlock()
	fake.RebootServerStub = nil
	if fake.rebootServerReturnsOnCall == nil {
		fake.rebootServerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.rebootServerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) SetMetadata(arg1 servers.Server, arg2 properties.ServerTags) error {
	fake.setMetadataMutex.Lock()
	ret, specificReturn := fake.setMetadataReturnsOnCall[len(fake.setMetadataArgsForCall)]
	fake.setMetadataArgsForCall = append(fake.setMetadataArgsForCall, struct {
		arg1 servers.Server
		arg2 properties.ServerTags
	}{arg1, arg2})
	stub := fake.SetMetadataStub
	fakeReturns := fake.setMetadataReturns
	fake.recordInvocation("SetMetadata", []interface{}{arg1, arg2})
	fake.setMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeComputeService) SetMetadataCallCount() int {
	fake.setMetadataMutex.RLock()
	defer fake.setMetadataMutex.RUnlock()
	return len(fake.setMetadataArgsForCall)
}

func (fake *FakeComputeService) SetMetadataCalls(stub func(servers.Server, properties.ServerTags) error) {
	fake.setMetadataMutex.Lock()
	defer fake.setMetadataMutex.Unlock()
	fake.SetMetadataStub = stub
}

func (fake *FakeComputeService) SetMetadataArgsForCall(i int) (servers.Server, properties.ServerTags) {
	fake.setMetadataMutex.RLock()
	defer fake.setMetadataMutex.RUnlock()
	argsForCall := fake.setMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeService) SetMetadataReturns(result1 error) {
	fake.setMetadataMutex.Lock()
	defer fake.setMetadataMutex.Unlock()
	fake.SetMetadataStub = nil
	fake.setMetadataReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) SetMetadataReturnsOnCall(i int, result1 error) {
	fake.setMetadataMutex.Lock()
	defer fake.setMetadataMutex.Unlock()
	fake.SetMetadataStub = nil
	if fake.setMetadataReturnsOnCall == nil {
		fake.setMetadataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setMetadataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	fake.getMatchingFlavorMutex.RLock()
	defer fake.getMatchingFlavorMutex.RUnlock()
	fake.getMetadataMutex.RLock()
	defer fake.getMetadataMutex.RUnlock()
	fake.getServerMutex.RLock()
	defer fake.getServerMutex.RUnlock()
	fake.rebootServerMutex.RLock()
	defer fake.rebootServerMutex.RUnlock()
	fake.setMetadataMutex.RLock()
	defer fake.setMetadataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeComputeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ compute.ComputeService = new(FakeComputeService)
