// Code generated by counterfeiter. DO NOT EDIT.
package computefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cpi-go/apiv1"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/compute"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/config"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
)

type FakeComputeService struct {
	CreateServerStub        func(apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, config.OpenstackConfig) (string, error)
	createServerMutex       sync.RWMutex
	createServerArgsForCall []struct {
		arg1 apiv1.StemcellCID
		arg2 properties.CreateVM
		arg3 properties.NetworkConfig
		arg4 config.OpenstackConfig
	}
	createServerReturns struct {
		result1 string
		result2 error
	}
	createServerReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeComputeService) CreateServer(arg1 apiv1.StemcellCID, arg2 properties.CreateVM, arg3 properties.NetworkConfig, arg4 config.OpenstackConfig) (string, error) {
	fake.createServerMutex.Lock()
	ret, specificReturn := fake.createServerReturnsOnCall[len(fake.createServerArgsForCall)]
	fake.createServerArgsForCall = append(fake.createServerArgsForCall, struct {
		arg1 apiv1.StemcellCID
		arg2 properties.CreateVM
		arg3 properties.NetworkConfig
		arg4 config.OpenstackConfig
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateServerStub
	fakeReturns := fake.createServerReturns
	fake.recordInvocation("CreateServer", []interface{}{arg1, arg2, arg3, arg4})
	fake.createServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeService) CreateServerCallCount() int {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	return len(fake.createServerArgsForCall)
}

func (fake *FakeComputeService) CreateServerCalls(stub func(apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, config.OpenstackConfig) (string, error)) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = stub
}

func (fake *FakeComputeService) CreateServerArgsForCall(i int) (apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, config.OpenstackConfig) {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	argsForCall := fake.createServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeComputeService) CreateServerReturns(result1 string, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	fake.createServerReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) CreateServerReturnsOnCall(i int, result1 string, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	if fake.createServerReturnsOnCall == nil {
		fake.createServerReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createServerReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeComputeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ compute.ComputeService = new(FakeComputeService)
