// Code generated by counterfeiter. DO NOT EDIT.
package computefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/compute"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/flavors"
)

type FakeFlavorResolver struct {
	ResolveFlavorForInstanceTypeStub        func(string) (flavors.Flavor, error)
	resolveFlavorForInstanceTypeMutex       sync.RWMutex
	resolveFlavorForInstanceTypeArgsForCall []struct {
		arg1 string
	}
	resolveFlavorForInstanceTypeReturns struct {
		result1 flavors.Flavor
		result2 error
	}
	resolveFlavorForInstanceTypeReturnsOnCall map[int]struct {
		result1 flavors.Flavor
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFlavorResolver) ResolveFlavorForInstanceType(arg1 string) (flavors.Flavor, error) {
	fake.resolveFlavorForInstanceTypeMutex.Lock()
	ret, specificReturn := fake.resolveFlavorForInstanceTypeReturnsOnCall[len(fake.resolveFlavorForInstanceTypeArgsForCall)]
	fake.resolveFlavorForInstanceTypeArgsForCall = append(fake.resolveFlavorForInstanceTypeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ResolveFlavorForInstanceTypeStub
	fakeReturns := fake.resolveFlavorForInstanceTypeReturns
	fake.recordInvocation("ResolveFlavorForInstanceType", []interface{}{arg1})
	fake.resolveFlavorForInstanceTypeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeFlavorResolver) ResolveFlavorForInstanceTypeCallCount() int {
	fake.resolveFlavorForInstanceTypeMutex.RLock()
	defer fake.resolveFlavorForInstanceTypeMutex.RUnlock()
	return len(fake.resolveFlavorForInstanceTypeArgsForCall)
}

func (fake *FakeFlavorResolver) ResolveFlavorForInstanceTypeCalls(stub func(string) (flavors.Flavor, error)) {
	fake.resolveFlavorForInstanceTypeMutex.Lock()
	defer fake.resolveFlavorForInstanceTypeMutex.Unlock()
	fake.ResolveFlavorForInstanceTypeStub = stub
}

func (fake *FakeFlavorResolver) ResolveFlavorForInstanceTypeArgsForCall(i int) string {
	fake.resolveFlavorForInstanceTypeMutex.RLock()
	defer fake.resolveFlavorForInstanceTypeMutex.RUnlock()
	argsForCall := fake.resolveFlavorForInstanceTypeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeFlavorResolver) ResolveFlavorForInstanceTypeReturns(result1 flavors.Flavor, result2 error) {
	fake.resolveFlavorForInstanceTypeMutex.Lock()
	defer fake.resolveFlavorForInstanceTypeMutex.Unlock()
	fake.ResolveFlavorForInstanceTypeStub = nil
	fake.resolveFlavorForInstanceTypeReturns = struct {
		result1 flavors.Flavor
		result2 error
	}{result1, result2}
}

func (fake *FakeFlavorResolver) ResolveFlavorForInstanceTypeReturnsOnCall(i int, result1 flavors.Flavor, result2 error) {
	fake.resolveFlavorForInstanceTypeMutex.Lock()
	defer fake.resolveFlavorForInstanceTypeMutex.Unlock()
	fake.ResolveFlavorForInstanceTypeStub = nil
	if fake.resolveFlavorForInstanceTypeReturnsOnCall == nil {
		fake.resolveFlavorForInstanceTypeReturnsOnCall = make(map[int]struct {
			result1 flavors.Flavor
			result2 error
		})
	}
	fake.resolveFlavorForInstanceTypeReturnsOnCall[i] = struct {
		result1 flavors.Flavor
		result2 error
	}{result1, result2}
}

func (fake *FakeFlavorResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.resolveFlavorForInstanceTypeMutex.RLock()
	defer fake.resolveFlavorForInstanceTypeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeFlavorResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ compute.FlavorResolver = new(FakeFlavorResolver)
