// Code generated by counterfeiter. DO NOT EDIT.
package computefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cpi-go/apiv1"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/compute"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/config"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
	"github.com/gophercloud/gophercloud/openstack/compute/v2/servers"
	"github.com/gophercloud/gophercloud/openstack/networking/v2/ports"
)

type FakeComputeService struct {
	CreateServerStub        func(apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, *ports.Port, apiv1.AgentID, apiv1.VMEnv, config.CpiConfig) (*servers.Server, error)
	createServerMutex       sync.RWMutex
	createServerArgsForCall []struct {
		arg1 apiv1.StemcellCID
		arg2 properties.CreateVM
		arg3 properties.NetworkConfig
		arg4 *ports.Port
		arg5 apiv1.AgentID
		arg6 apiv1.VMEnv
		arg7 config.CpiConfig
	}
	createServerReturns struct {
		result1 *servers.Server
		result2 error
	}
	createServerReturnsOnCall map[int]struct {
		result1 *servers.Server
		result2 error
	}
	DeleteServerStub        func(string, config.OpenstackConfig) error
	deleteServerMutex       sync.RWMutex
	deleteServerArgsForCall []struct {
		arg1 string
		arg2 config.OpenstackConfig
	}
	deleteServerReturns struct {
		result1 error
	}
	deleteServerReturnsOnCall map[int]struct {
		result1 error
	}
	SetMetadataStub        func(servers.Server, properties.ServerTags) error
	setMetadataMutex       sync.RWMutex
	setMetadataArgsForCall []struct {
		arg1 servers.Server
		arg2 properties.ServerTags
	}
	setMetadataReturns struct {
		result1 error
	}
	setMetadataReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeComputeService) CreateServer(arg1 apiv1.StemcellCID, arg2 properties.CreateVM, arg3 properties.NetworkConfig, arg4 *ports.Port, arg5 apiv1.AgentID, arg6 apiv1.VMEnv, arg7 config.CpiConfig) (*servers.Server, error) {
	fake.createServerMutex.Lock()
	ret, specificReturn := fake.createServerReturnsOnCall[len(fake.createServerArgsForCall)]
	fake.createServerArgsForCall = append(fake.createServerArgsForCall, struct {
		arg1 apiv1.StemcellCID
		arg2 properties.CreateVM
		arg3 properties.NetworkConfig
		arg4 *ports.Port
		arg5 apiv1.AgentID
		arg6 apiv1.VMEnv
		arg7 config.CpiConfig
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	stub := fake.CreateServerStub
	fakeReturns := fake.createServerReturns
	fake.recordInvocation("CreateServer", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.createServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeComputeService) CreateServerCallCount() int {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	return len(fake.createServerArgsForCall)
}

func (fake *FakeComputeService) CreateServerCalls(stub func(apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, *ports.Port, apiv1.AgentID, apiv1.VMEnv, config.CpiConfig) (*servers.Server, error)) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = stub
}

func (fake *FakeComputeService) CreateServerArgsForCall(i int) (apiv1.StemcellCID, properties.CreateVM, properties.NetworkConfig, *ports.Port, apiv1.AgentID, apiv1.VMEnv, config.CpiConfig) {
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	argsForCall := fake.createServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7
}

func (fake *FakeComputeService) CreateServerReturns(result1 *servers.Server, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	fake.createServerReturns = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) CreateServerReturnsOnCall(i int, result1 *servers.Server, result2 error) {
	fake.createServerMutex.Lock()
	defer fake.createServerMutex.Unlock()
	fake.CreateServerStub = nil
	if fake.createServerReturnsOnCall == nil {
		fake.createServerReturnsOnCall = make(map[int]struct {
			result1 *servers.Server
			result2 error
		})
	}
	fake.createServerReturnsOnCall[i] = struct {
		result1 *servers.Server
		result2 error
	}{result1, result2}
}

func (fake *FakeComputeService) DeleteServer(arg1 string, arg2 config.OpenstackConfig) error {
	fake.deleteServerMutex.Lock()
	ret, specificReturn := fake.deleteServerReturnsOnCall[len(fake.deleteServerArgsForCall)]
	fake.deleteServerArgsForCall = append(fake.deleteServerArgsForCall, struct {
		arg1 string
		arg2 config.OpenstackConfig
	}{arg1, arg2})
	stub := fake.DeleteServerStub
	fakeReturns := fake.deleteServerReturns
	fake.recordInvocation("DeleteServer", []interface{}{arg1, arg2})
	fake.deleteServerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeComputeService) DeleteServerCallCount() int {
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	return len(fake.deleteServerArgsForCall)
}

func (fake *FakeComputeService) DeleteServerCalls(stub func(string, config.OpenstackConfig) error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = stub
}

func (fake *FakeComputeService) DeleteServerArgsForCall(i int) (string, config.OpenstackConfig) {
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	argsForCall := fake.deleteServerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeService) DeleteServerReturns(result1 error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = nil
	fake.deleteServerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) DeleteServerReturnsOnCall(i int, result1 error) {
	fake.deleteServerMutex.Lock()
	defer fake.deleteServerMutex.Unlock()
	fake.DeleteServerStub = nil
	if fake.deleteServerReturnsOnCall == nil {
		fake.deleteServerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteServerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) SetMetadata(arg1 servers.Server, arg2 properties.ServerTags) error {
	fake.setMetadataMutex.Lock()
	ret, specificReturn := fake.setMetadataReturnsOnCall[len(fake.setMetadataArgsForCall)]
	fake.setMetadataArgsForCall = append(fake.setMetadataArgsForCall, struct {
		arg1 servers.Server
		arg2 properties.ServerTags
	}{arg1, arg2})
	stub := fake.SetMetadataStub
	fakeReturns := fake.setMetadataReturns
	fake.recordInvocation("SetMetadata", []interface{}{arg1, arg2})
	fake.setMetadataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeComputeService) SetMetadataCallCount() int {
	fake.setMetadataMutex.RLock()
	defer fake.setMetadataMutex.RUnlock()
	return len(fake.setMetadataArgsForCall)
}

func (fake *FakeComputeService) SetMetadataCalls(stub func(servers.Server, properties.ServerTags) error) {
	fake.setMetadataMutex.Lock()
	defer fake.setMetadataMutex.Unlock()
	fake.SetMetadataStub = stub
}

func (fake *FakeComputeService) SetMetadataArgsForCall(i int) (servers.Server, properties.ServerTags) {
	fake.setMetadataMutex.RLock()
	defer fake.setMetadataMutex.RUnlock()
	argsForCall := fake.setMetadataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeComputeService) SetMetadataReturns(result1 error) {
	fake.setMetadataMutex.Lock()
	defer fake.setMetadataMutex.Unlock()
	fake.SetMetadataStub = nil
	fake.setMetadataReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) SetMetadataReturnsOnCall(i int, result1 error) {
	fake.setMetadataMutex.Lock()
	defer fake.setMetadataMutex.Unlock()
	fake.SetMetadataStub = nil
	if fake.setMetadataReturnsOnCall == nil {
		fake.setMetadataReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.setMetadataReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeComputeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createServerMutex.RLock()
	defer fake.createServerMutex.RUnlock()
	fake.deleteServerMutex.RLock()
	defer fake.deleteServerMutex.RUnlock()
	fake.setMetadataMutex.RLock()
	defer fake.setMetadataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeComputeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ compute.ComputeService = new(FakeComputeService)
