// Code generated by counterfeiter. DO NOT EDIT.
package networkfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/network"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
)

type FakeNetworkService struct {
	ConfigureNetworkStub        func(string, properties.NetworkConfig) error
	configureNetworkMutex       sync.RWMutex
	configureNetworkArgsForCall []struct {
		arg1 string
		arg2 properties.NetworkConfig
	}
	configureNetworkReturns struct {
		result1 error
	}
	configureNetworkReturnsOnCall map[int]struct {
		result1 error
	}
	ResolveSecurityGroupsStub        func([]string) ([]string, error)
	resolveSecurityGroupsMutex       sync.RWMutex
	resolveSecurityGroupsArgsForCall []struct {
		arg1 []string
	}
	resolveSecurityGroupsReturns struct {
		result1 []string
		result2 error
	}
	resolveSecurityGroupsReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNetworkService) ConfigureNetwork(arg1 string, arg2 properties.NetworkConfig) error {
	fake.configureNetworkMutex.Lock()
	ret, specificReturn := fake.configureNetworkReturnsOnCall[len(fake.configureNetworkArgsForCall)]
	fake.configureNetworkArgsForCall = append(fake.configureNetworkArgsForCall, struct {
		arg1 string
		arg2 properties.NetworkConfig
	}{arg1, arg2})
	stub := fake.ConfigureNetworkStub
	fakeReturns := fake.configureNetworkReturns
	fake.recordInvocation("ConfigureNetwork", []interface{}{arg1, arg2})
	fake.configureNetworkMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkService) ConfigureNetworkCallCount() int {
	fake.configureNetworkMutex.RLock()
	defer fake.configureNetworkMutex.RUnlock()
	return len(fake.configureNetworkArgsForCall)
}

func (fake *FakeNetworkService) ConfigureNetworkCalls(stub func(string, properties.NetworkConfig) error) {
	fake.configureNetworkMutex.Lock()
	defer fake.configureNetworkMutex.Unlock()
	fake.ConfigureNetworkStub = stub
}

func (fake *FakeNetworkService) ConfigureNetworkArgsForCall(i int) (string, properties.NetworkConfig) {
	fake.configureNetworkMutex.RLock()
	defer fake.configureNetworkMutex.RUnlock()
	argsForCall := fake.configureNetworkArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNetworkService) ConfigureNetworkReturns(result1 error) {
	fake.configureNetworkMutex.Lock()
	defer fake.configureNetworkMutex.Unlock()
	fake.ConfigureNetworkStub = nil
	fake.configureNetworkReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNetworkService) ConfigureNetworkReturnsOnCall(i int, result1 error) {
	fake.configureNetworkMutex.Lock()
	defer fake.configureNetworkMutex.Unlock()
	fake.ConfigureNetworkStub = nil
	if fake.configureNetworkReturnsOnCall == nil {
		fake.configureNetworkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.configureNetworkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNetworkService) ResolveSecurityGroups(arg1 []string) ([]string, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.resolveSecurityGroupsMutex.Lock()
	ret, specificReturn := fake.resolveSecurityGroupsReturnsOnCall[len(fake.resolveSecurityGroupsArgsForCall)]
	fake.resolveSecurityGroupsArgsForCall = append(fake.resolveSecurityGroupsArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	stub := fake.ResolveSecurityGroupsStub
	fakeReturns := fake.resolveSecurityGroupsReturns
	fake.recordInvocation("ResolveSecurityGroups", []interface{}{arg1Copy})
	fake.resolveSecurityGroupsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNetworkService) ResolveSecurityGroupsCallCount() int {
	fake.resolveSecurityGroupsMutex.RLock()
	defer fake.resolveSecurityGroupsMutex.RUnlock()
	return len(fake.resolveSecurityGroupsArgsForCall)
}

func (fake *FakeNetworkService) ResolveSecurityGroupsCalls(stub func([]string) ([]string, error)) {
	fake.resolveSecurityGroupsMutex.Lock()
	defer fake.resolveSecurityGroupsMutex.Unlock()
	fake.ResolveSecurityGroupsStub = stub
}

func (fake *FakeNetworkService) ResolveSecurityGroupsArgsForCall(i int) []string {
	fake.resolveSecurityGroupsMutex.RLock()
	defer fake.resolveSecurityGroupsMutex.RUnlock()
	argsForCall := fake.resolveSecurityGroupsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeNetworkService) ResolveSecurityGroupsReturns(result1 []string, result2 error) {
	fake.resolveSecurityGroupsMutex.Lock()
	defer fake.resolveSecurityGroupsMutex.Unlock()
	fake.ResolveSecurityGroupsStub = nil
	fake.resolveSecurityGroupsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) ResolveSecurityGroupsReturnsOnCall(i int, result1 []string, result2 error) {
	fake.resolveSecurityGroupsMutex.Lock()
	defer fake.resolveSecurityGroupsMutex.Unlock()
	fake.ResolveSecurityGroupsStub = nil
	if fake.resolveSecurityGroupsReturnsOnCall == nil {
		fake.resolveSecurityGroupsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.resolveSecurityGroupsReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.configureNetworkMutex.RLock()
	defer fake.configureNetworkMutex.RUnlock()
	fake.resolveSecurityGroupsMutex.RLock()
	defer fake.resolveSecurityGroupsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNetworkService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network.NetworkService = new(FakeNetworkService)
