// Code generated by counterfeiter. DO NOT EDIT.
package networkfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-cpi-go/apiv1"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/config"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/network"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
	"github.com/gophercloud/gophercloud/openstack/networking/v2/ports"
)

type FakeNetworkService struct {
	ConfigureVIPNetworkStub        func(string, properties.NetworkConfig) error
	configureVIPNetworkMutex       sync.RWMutex
	configureVIPNetworkArgsForCall []struct {
		arg1 string
		arg2 properties.NetworkConfig
	}
	configureVIPNetworkReturns struct {
		result1 error
	}
	configureVIPNetworkReturnsOnCall map[int]struct {
		result1 error
	}
	CreatePortStub        func(properties.NetworkConfig, properties.CreateVM) (*ports.Port, error)
	createPortMutex       sync.RWMutex
	createPortArgsForCall []struct {
		arg1 properties.NetworkConfig
		arg2 properties.CreateVM
	}
	createPortReturns struct {
		result1 *ports.Port
		result2 error
	}
	createPortReturnsOnCall map[int]struct {
		result1 *ports.Port
		result2 error
	}
	GetNetworkConfigurationStub        func(apiv1.Networks, config.OpenstackConfig, properties.CreateVM) (properties.NetworkConfig, error)
	getNetworkConfigurationMutex       sync.RWMutex
	getNetworkConfigurationArgsForCall []struct {
		arg1 apiv1.Networks
		arg2 config.OpenstackConfig
		arg3 properties.CreateVM
	}
	getNetworkConfigurationReturns struct {
		result1 properties.NetworkConfig
		result2 error
	}
	getNetworkConfigurationReturnsOnCall map[int]struct {
		result1 properties.NetworkConfig
		result2 error
	}
	GetSubnetIDStub        func(string, string) (string, error)
	getSubnetIDMutex       sync.RWMutex
	getSubnetIDArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getSubnetIDReturns struct {
		result1 string
		result2 error
	}
	getSubnetIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNetworkService) ConfigureVIPNetwork(arg1 string, arg2 properties.NetworkConfig) error {
	fake.configureVIPNetworkMutex.Lock()
	ret, specificReturn := fake.configureVIPNetworkReturnsOnCall[len(fake.configureVIPNetworkArgsForCall)]
	fake.configureVIPNetworkArgsForCall = append(fake.configureVIPNetworkArgsForCall, struct {
		arg1 string
		arg2 properties.NetworkConfig
	}{arg1, arg2})
	stub := fake.ConfigureVIPNetworkStub
	fakeReturns := fake.configureVIPNetworkReturns
	fake.recordInvocation("ConfigureVIPNetwork", []interface{}{arg1, arg2})
	fake.configureVIPNetworkMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkService) ConfigureVIPNetworkCallCount() int {
	fake.configureVIPNetworkMutex.RLock()
	defer fake.configureVIPNetworkMutex.RUnlock()
	return len(fake.configureVIPNetworkArgsForCall)
}

func (fake *FakeNetworkService) ConfigureVIPNetworkCalls(stub func(string, properties.NetworkConfig) error) {
	fake.configureVIPNetworkMutex.Lock()
	defer fake.configureVIPNetworkMutex.Unlock()
	fake.ConfigureVIPNetworkStub = stub
}

func (fake *FakeNetworkService) ConfigureVIPNetworkArgsForCall(i int) (string, properties.NetworkConfig) {
	fake.configureVIPNetworkMutex.RLock()
	defer fake.configureVIPNetworkMutex.RUnlock()
	argsForCall := fake.configureVIPNetworkArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNetworkService) ConfigureVIPNetworkReturns(result1 error) {
	fake.configureVIPNetworkMutex.Lock()
	defer fake.configureVIPNetworkMutex.Unlock()
	fake.ConfigureVIPNetworkStub = nil
	fake.configureVIPNetworkReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNetworkService) ConfigureVIPNetworkReturnsOnCall(i int, result1 error) {
	fake.configureVIPNetworkMutex.Lock()
	defer fake.configureVIPNetworkMutex.Unlock()
	fake.ConfigureVIPNetworkStub = nil
	if fake.configureVIPNetworkReturnsOnCall == nil {
		fake.configureVIPNetworkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.configureVIPNetworkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeNetworkService) CreatePort(arg1 properties.NetworkConfig, arg2 properties.CreateVM) (*ports.Port, error) {
	fake.createPortMutex.Lock()
	ret, specificReturn := fake.createPortReturnsOnCall[len(fake.createPortArgsForCall)]
	fake.createPortArgsForCall = append(fake.createPortArgsForCall, struct {
		arg1 properties.NetworkConfig
		arg2 properties.CreateVM
	}{arg1, arg2})
	stub := fake.CreatePortStub
	fakeReturns := fake.createPortReturns
	fake.recordInvocation("CreatePort", []interface{}{arg1, arg2})
	fake.createPortMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNetworkService) CreatePortCallCount() int {
	fake.createPortMutex.RLock()
	defer fake.createPortMutex.RUnlock()
	return len(fake.createPortArgsForCall)
}

func (fake *FakeNetworkService) CreatePortCalls(stub func(properties.NetworkConfig, properties.CreateVM) (*ports.Port, error)) {
	fake.createPortMutex.Lock()
	defer fake.createPortMutex.Unlock()
	fake.CreatePortStub = stub
}

func (fake *FakeNetworkService) CreatePortArgsForCall(i int) (properties.NetworkConfig, properties.CreateVM) {
	fake.createPortMutex.RLock()
	defer fake.createPortMutex.RUnlock()
	argsForCall := fake.createPortArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNetworkService) CreatePortReturns(result1 *ports.Port, result2 error) {
	fake.createPortMutex.Lock()
	defer fake.createPortMutex.Unlock()
	fake.CreatePortStub = nil
	fake.createPortReturns = struct {
		result1 *ports.Port
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) CreatePortReturnsOnCall(i int, result1 *ports.Port, result2 error) {
	fake.createPortMutex.Lock()
	defer fake.createPortMutex.Unlock()
	fake.CreatePortStub = nil
	if fake.createPortReturnsOnCall == nil {
		fake.createPortReturnsOnCall = make(map[int]struct {
			result1 *ports.Port
			result2 error
		})
	}
	fake.createPortReturnsOnCall[i] = struct {
		result1 *ports.Port
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) GetNetworkConfiguration(arg1 apiv1.Networks, arg2 config.OpenstackConfig, arg3 properties.CreateVM) (properties.NetworkConfig, error) {
	fake.getNetworkConfigurationMutex.Lock()
	ret, specificReturn := fake.getNetworkConfigurationReturnsOnCall[len(fake.getNetworkConfigurationArgsForCall)]
	fake.getNetworkConfigurationArgsForCall = append(fake.getNetworkConfigurationArgsForCall, struct {
		arg1 apiv1.Networks
		arg2 config.OpenstackConfig
		arg3 properties.CreateVM
	}{arg1, arg2, arg3})
	stub := fake.GetNetworkConfigurationStub
	fakeReturns := fake.getNetworkConfigurationReturns
	fake.recordInvocation("GetNetworkConfiguration", []interface{}{arg1, arg2, arg3})
	fake.getNetworkConfigurationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNetworkService) GetNetworkConfigurationCallCount() int {
	fake.getNetworkConfigurationMutex.RLock()
	defer fake.getNetworkConfigurationMutex.RUnlock()
	return len(fake.getNetworkConfigurationArgsForCall)
}

func (fake *FakeNetworkService) GetNetworkConfigurationCalls(stub func(apiv1.Networks, config.OpenstackConfig, properties.CreateVM) (properties.NetworkConfig, error)) {
	fake.getNetworkConfigurationMutex.Lock()
	defer fake.getNetworkConfigurationMutex.Unlock()
	fake.GetNetworkConfigurationStub = stub
}

func (fake *FakeNetworkService) GetNetworkConfigurationArgsForCall(i int) (apiv1.Networks, config.OpenstackConfig, properties.CreateVM) {
	fake.getNetworkConfigurationMutex.RLock()
	defer fake.getNetworkConfigurationMutex.RUnlock()
	argsForCall := fake.getNetworkConfigurationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeNetworkService) GetNetworkConfigurationReturns(result1 properties.NetworkConfig, result2 error) {
	fake.getNetworkConfigurationMutex.Lock()
	defer fake.getNetworkConfigurationMutex.Unlock()
	fake.GetNetworkConfigurationStub = nil
	fake.getNetworkConfigurationReturns = struct {
		result1 properties.NetworkConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) GetNetworkConfigurationReturnsOnCall(i int, result1 properties.NetworkConfig, result2 error) {
	fake.getNetworkConfigurationMutex.Lock()
	defer fake.getNetworkConfigurationMutex.Unlock()
	fake.GetNetworkConfigurationStub = nil
	if fake.getNetworkConfigurationReturnsOnCall == nil {
		fake.getNetworkConfigurationReturnsOnCall = make(map[int]struct {
			result1 properties.NetworkConfig
			result2 error
		})
	}
	fake.getNetworkConfigurationReturnsOnCall[i] = struct {
		result1 properties.NetworkConfig
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) GetSubnetID(arg1 string, arg2 string) (string, error) {
	fake.getSubnetIDMutex.Lock()
	ret, specificReturn := fake.getSubnetIDReturnsOnCall[len(fake.getSubnetIDArgsForCall)]
	fake.getSubnetIDArgsForCall = append(fake.getSubnetIDArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	stub := fake.GetSubnetIDStub
	fakeReturns := fake.getSubnetIDReturns
	fake.recordInvocation("GetSubnetID", []interface{}{arg1, arg2})
	fake.getSubnetIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNetworkService) GetSubnetIDCallCount() int {
	fake.getSubnetIDMutex.RLock()
	defer fake.getSubnetIDMutex.RUnlock()
	return len(fake.getSubnetIDArgsForCall)
}

func (fake *FakeNetworkService) GetSubnetIDCalls(stub func(string, string) (string, error)) {
	fake.getSubnetIDMutex.Lock()
	defer fake.getSubnetIDMutex.Unlock()
	fake.GetSubnetIDStub = stub
}

func (fake *FakeNetworkService) GetSubnetIDArgsForCall(i int) (string, string) {
	fake.getSubnetIDMutex.RLock()
	defer fake.getSubnetIDMutex.RUnlock()
	argsForCall := fake.getSubnetIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeNetworkService) GetSubnetIDReturns(result1 string, result2 error) {
	fake.getSubnetIDMutex.Lock()
	defer fake.getSubnetIDMutex.Unlock()
	fake.GetSubnetIDStub = nil
	fake.getSubnetIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) GetSubnetIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.getSubnetIDMutex.Lock()
	defer fake.getSubnetIDMutex.Unlock()
	fake.GetSubnetIDStub = nil
	if fake.getSubnetIDReturnsOnCall == nil {
		fake.getSubnetIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getSubnetIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeNetworkService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.configureVIPNetworkMutex.RLock()
	defer fake.configureVIPNetworkMutex.RUnlock()
	fake.createPortMutex.RLock()
	defer fake.createPortMutex.RUnlock()
	fake.getNetworkConfigurationMutex.RLock()
	defer fake.getNetworkConfigurationMutex.RUnlock()
	fake.getSubnetIDMutex.RLock()
	defer fake.getSubnetIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNetworkService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ network.NetworkService = new(FakeNetworkService)
