// Code generated by counterfeiter. DO NOT EDIT.
package volumefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/utils"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/volume"
	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes"
)

type FakeVolumeFacade struct {
	CreateDiskStub        func(utils.ServiceClient, volumes.CreateOptsBuilder) (*volumes.Volume, error)
	createDiskMutex       sync.RWMutex
	createDiskArgsForCall []struct {
		arg1 utils.ServiceClient
		arg2 volumes.CreateOptsBuilder
	}
	createDiskReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	createDiskReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	GetVolumeStub        func(utils.RetryableServiceClient, string) (*volumes.Volume, error)
	getVolumeMutex       sync.RWMutex
	getVolumeArgsForCall []struct {
		arg1 utils.RetryableServiceClient
		arg2 string
	}
	getVolumeReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	getVolumeReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVolumeFacade) CreateDisk(arg1 utils.ServiceClient, arg2 volumes.CreateOptsBuilder) (*volumes.Volume, error) {
	fake.createDiskMutex.Lock()
	ret, specificReturn := fake.createDiskReturnsOnCall[len(fake.createDiskArgsForCall)]
	fake.createDiskArgsForCall = append(fake.createDiskArgsForCall, struct {
		arg1 utils.ServiceClient
		arg2 volumes.CreateOptsBuilder
	}{arg1, arg2})
	stub := fake.CreateDiskStub
	fakeReturns := fake.createDiskReturns
	fake.recordInvocation("CreateDisk", []interface{}{arg1, arg2})
	fake.createDiskMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeFacade) CreateDiskCallCount() int {
	fake.createDiskMutex.RLock()
	defer fake.createDiskMutex.RUnlock()
	return len(fake.createDiskArgsForCall)
}

func (fake *FakeVolumeFacade) CreateDiskCalls(stub func(utils.ServiceClient, volumes.CreateOptsBuilder) (*volumes.Volume, error)) {
	fake.createDiskMutex.Lock()
	defer fake.createDiskMutex.Unlock()
	fake.CreateDiskStub = stub
}

func (fake *FakeVolumeFacade) CreateDiskArgsForCall(i int) (utils.ServiceClient, volumes.CreateOptsBuilder) {
	fake.createDiskMutex.RLock()
	defer fake.createDiskMutex.RUnlock()
	argsForCall := fake.createDiskArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeFacade) CreateDiskReturns(result1 *volumes.Volume, result2 error) {
	fake.createDiskMutex.Lock()
	defer fake.createDiskMutex.Unlock()
	fake.CreateDiskStub = nil
	fake.createDiskReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) CreateDiskReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.createDiskMutex.Lock()
	defer fake.createDiskMutex.Unlock()
	fake.CreateDiskStub = nil
	if fake.createDiskReturnsOnCall == nil {
		fake.createDiskReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.createDiskReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) GetVolume(arg1 utils.RetryableServiceClient, arg2 string) (*volumes.Volume, error) {
	fake.getVolumeMutex.Lock()
	ret, specificReturn := fake.getVolumeReturnsOnCall[len(fake.getVolumeArgsForCall)]
	fake.getVolumeArgsForCall = append(fake.getVolumeArgsForCall, struct {
		arg1 utils.RetryableServiceClient
		arg2 string
	}{arg1, arg2})
	stub := fake.GetVolumeStub
	fakeReturns := fake.getVolumeReturns
	fake.recordInvocation("GetVolume", []interface{}{arg1, arg2})
	fake.getVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeFacade) GetVolumeCallCount() int {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	return len(fake.getVolumeArgsForCall)
}

func (fake *FakeVolumeFacade) GetVolumeCalls(stub func(utils.RetryableServiceClient, string) (*volumes.Volume, error)) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = stub
}

func (fake *FakeVolumeFacade) GetVolumeArgsForCall(i int) (utils.RetryableServiceClient, string) {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	argsForCall := fake.getVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeFacade) GetVolumeReturns(result1 *volumes.Volume, result2 error) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = nil
	fake.getVolumeReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) GetVolumeReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = nil
	if fake.getVolumeReturnsOnCall == nil {
		fake.getVolumeReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.getVolumeReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createDiskMutex.RLock()
	defer fake.createDiskMutex.RUnlock()
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVolumeFacade) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ volume.VolumeFacade = new(FakeVolumeFacade)
