// Code generated by counterfeiter. DO NOT EDIT.
package volumefakes

import (
	"sync"
	"time"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/volume"
	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes"
)

type FakeVolumeService struct {
	CreateVolumeStub        func(int, properties.CreateDisk, string) (*volumes.Volume, error)
	createVolumeMutex       sync.RWMutex
	createVolumeArgsForCall []struct {
		arg1 int
		arg2 properties.CreateDisk
		arg3 string
	}
	createVolumeReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	createVolumeReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	WaitForVolumeToBecomeAvailableStub        func(string, time.Duration) (*volumes.Volume, error)
	waitForVolumeToBecomeAvailableMutex       sync.RWMutex
	waitForVolumeToBecomeAvailableArgsForCall []struct {
		arg1 string
		arg2 time.Duration
	}
	waitForVolumeToBecomeAvailableReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	waitForVolumeToBecomeAvailableReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVolumeService) CreateVolume(arg1 int, arg2 properties.CreateDisk, arg3 string) (*volumes.Volume, error) {
	fake.createVolumeMutex.Lock()
	ret, specificReturn := fake.createVolumeReturnsOnCall[len(fake.createVolumeArgsForCall)]
	fake.createVolumeArgsForCall = append(fake.createVolumeArgsForCall, struct {
		arg1 int
		arg2 properties.CreateDisk
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CreateVolumeStub
	fakeReturns := fake.createVolumeReturns
	fake.recordInvocation("CreateVolume", []interface{}{arg1, arg2, arg3})
	fake.createVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeService) CreateVolumeCallCount() int {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return len(fake.createVolumeArgsForCall)
}

func (fake *FakeVolumeService) CreateVolumeCalls(stub func(int, properties.CreateDisk, string) (*volumes.Volume, error)) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = stub
}

func (fake *FakeVolumeService) CreateVolumeArgsForCall(i int) (int, properties.CreateDisk, string) {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	argsForCall := fake.createVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVolumeService) CreateVolumeReturns(result1 *volumes.Volume, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	fake.createVolumeReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) CreateVolumeReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	if fake.createVolumeReturnsOnCall == nil {
		fake.createVolumeReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.createVolumeReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeAvailable(arg1 string, arg2 time.Duration) (*volumes.Volume, error) {
	fake.waitForVolumeToBecomeAvailableMutex.Lock()
	ret, specificReturn := fake.waitForVolumeToBecomeAvailableReturnsOnCall[len(fake.waitForVolumeToBecomeAvailableArgsForCall)]
	fake.waitForVolumeToBecomeAvailableArgsForCall = append(fake.waitForVolumeToBecomeAvailableArgsForCall, struct {
		arg1 string
		arg2 time.Duration
	}{arg1, arg2})
	stub := fake.WaitForVolumeToBecomeAvailableStub
	fakeReturns := fake.waitForVolumeToBecomeAvailableReturns
	fake.recordInvocation("WaitForVolumeToBecomeAvailable", []interface{}{arg1, arg2})
	fake.waitForVolumeToBecomeAvailableMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeAvailableCallCount() int {
	fake.waitForVolumeToBecomeAvailableMutex.RLock()
	defer fake.waitForVolumeToBecomeAvailableMutex.RUnlock()
	return len(fake.waitForVolumeToBecomeAvailableArgsForCall)
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeAvailableCalls(stub func(string, time.Duration) (*volumes.Volume, error)) {
	fake.waitForVolumeToBecomeAvailableMutex.Lock()
	defer fake.waitForVolumeToBecomeAvailableMutex.Unlock()
	fake.WaitForVolumeToBecomeAvailableStub = stub
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeAvailableArgsForCall(i int) (string, time.Duration) {
	fake.waitForVolumeToBecomeAvailableMutex.RLock()
	defer fake.waitForVolumeToBecomeAvailableMutex.RUnlock()
	argsForCall := fake.waitForVolumeToBecomeAvailableArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeAvailableReturns(result1 *volumes.Volume, result2 error) {
	fake.waitForVolumeToBecomeAvailableMutex.Lock()
	defer fake.waitForVolumeToBecomeAvailableMutex.Unlock()
	fake.WaitForVolumeToBecomeAvailableStub = nil
	fake.waitForVolumeToBecomeAvailableReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeAvailableReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.waitForVolumeToBecomeAvailableMutex.Lock()
	defer fake.waitForVolumeToBecomeAvailableMutex.Unlock()
	fake.WaitForVolumeToBecomeAvailableStub = nil
	if fake.waitForVolumeToBecomeAvailableReturnsOnCall == nil {
		fake.waitForVolumeToBecomeAvailableReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.waitForVolumeToBecomeAvailableReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	fake.waitForVolumeToBecomeAvailableMutex.RLock()
	defer fake.waitForVolumeToBecomeAvailableMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVolumeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ volume.VolumeService = new(FakeVolumeService)
