// Code generated by counterfeiter. DO NOT EDIT.
package volumefakes

import (
	"sync"
	"time"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/volume"
	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes"
)

type FakeVolumeService struct {
	CreateVolumeStub        func(int, properties.CreateDisk, string) (*volumes.Volume, error)
	createVolumeMutex       sync.RWMutex
	createVolumeArgsForCall []struct {
		arg1 int
		arg2 properties.CreateDisk
		arg3 string
	}
	createVolumeReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	createVolumeReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	DeleteVolumeStub        func(string) error
	deleteVolumeMutex       sync.RWMutex
	deleteVolumeArgsForCall []struct {
		arg1 string
	}
	deleteVolumeReturns struct {
		result1 error
	}
	deleteVolumeReturnsOnCall map[int]struct {
		result1 error
	}
	ExtendVolumeSizeStub        func(string, int) error
	extendVolumeSizeMutex       sync.RWMutex
	extendVolumeSizeArgsForCall []struct {
		arg1 string
		arg2 int
	}
	extendVolumeSizeReturns struct {
		result1 error
	}
	extendVolumeSizeReturnsOnCall map[int]struct {
		result1 error
	}
	GetVolumeStub        func(string) (*volumes.Volume, error)
	getVolumeMutex       sync.RWMutex
	getVolumeArgsForCall []struct {
		arg1 string
	}
	getVolumeReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	getVolumeReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	WaitForVolumeToBecomeStatusStub        func(string, time.Duration, string) error
	waitForVolumeToBecomeStatusMutex       sync.RWMutex
	waitForVolumeToBecomeStatusArgsForCall []struct {
		arg1 string
		arg2 time.Duration
		arg3 string
	}
	waitForVolumeToBecomeStatusReturns struct {
		result1 error
	}
	waitForVolumeToBecomeStatusReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVolumeService) CreateVolume(arg1 int, arg2 properties.CreateDisk, arg3 string) (*volumes.Volume, error) {
	fake.createVolumeMutex.Lock()
	ret, specificReturn := fake.createVolumeReturnsOnCall[len(fake.createVolumeArgsForCall)]
	fake.createVolumeArgsForCall = append(fake.createVolumeArgsForCall, struct {
		arg1 int
		arg2 properties.CreateDisk
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.CreateVolumeStub
	fakeReturns := fake.createVolumeReturns
	fake.recordInvocation("CreateVolume", []interface{}{arg1, arg2, arg3})
	fake.createVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeService) CreateVolumeCallCount() int {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return len(fake.createVolumeArgsForCall)
}

func (fake *FakeVolumeService) CreateVolumeCalls(stub func(int, properties.CreateDisk, string) (*volumes.Volume, error)) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = stub
}

func (fake *FakeVolumeService) CreateVolumeArgsForCall(i int) (int, properties.CreateDisk, string) {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	argsForCall := fake.createVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVolumeService) CreateVolumeReturns(result1 *volumes.Volume, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	fake.createVolumeReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) CreateVolumeReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	if fake.createVolumeReturnsOnCall == nil {
		fake.createVolumeReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.createVolumeReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) DeleteVolume(arg1 string) error {
	fake.deleteVolumeMutex.Lock()
	ret, specificReturn := fake.deleteVolumeReturnsOnCall[len(fake.deleteVolumeArgsForCall)]
	fake.deleteVolumeArgsForCall = append(fake.deleteVolumeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.DeleteVolumeStub
	fakeReturns := fake.deleteVolumeReturns
	fake.recordInvocation("DeleteVolume", []interface{}{arg1})
	fake.deleteVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeService) DeleteVolumeCallCount() int {
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	return len(fake.deleteVolumeArgsForCall)
}

func (fake *FakeVolumeService) DeleteVolumeCalls(stub func(string) error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = stub
}

func (fake *FakeVolumeService) DeleteVolumeArgsForCall(i int) string {
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	argsForCall := fake.deleteVolumeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVolumeService) DeleteVolumeReturns(result1 error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = nil
	fake.deleteVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeService) DeleteVolumeReturnsOnCall(i int, result1 error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = nil
	if fake.deleteVolumeReturnsOnCall == nil {
		fake.deleteVolumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVolumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeService) ExtendVolumeSize(arg1 string, arg2 int) error {
	fake.extendVolumeSizeMutex.Lock()
	ret, specificReturn := fake.extendVolumeSizeReturnsOnCall[len(fake.extendVolumeSizeArgsForCall)]
	fake.extendVolumeSizeArgsForCall = append(fake.extendVolumeSizeArgsForCall, struct {
		arg1 string
		arg2 int
	}{arg1, arg2})
	stub := fake.ExtendVolumeSizeStub
	fakeReturns := fake.extendVolumeSizeReturns
	fake.recordInvocation("ExtendVolumeSize", []interface{}{arg1, arg2})
	fake.extendVolumeSizeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeService) ExtendVolumeSizeCallCount() int {
	fake.extendVolumeSizeMutex.RLock()
	defer fake.extendVolumeSizeMutex.RUnlock()
	return len(fake.extendVolumeSizeArgsForCall)
}

func (fake *FakeVolumeService) ExtendVolumeSizeCalls(stub func(string, int) error) {
	fake.extendVolumeSizeMutex.Lock()
	defer fake.extendVolumeSizeMutex.Unlock()
	fake.ExtendVolumeSizeStub = stub
}

func (fake *FakeVolumeService) ExtendVolumeSizeArgsForCall(i int) (string, int) {
	fake.extendVolumeSizeMutex.RLock()
	defer fake.extendVolumeSizeMutex.RUnlock()
	argsForCall := fake.extendVolumeSizeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeService) ExtendVolumeSizeReturns(result1 error) {
	fake.extendVolumeSizeMutex.Lock()
	defer fake.extendVolumeSizeMutex.Unlock()
	fake.ExtendVolumeSizeStub = nil
	fake.extendVolumeSizeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeService) ExtendVolumeSizeReturnsOnCall(i int, result1 error) {
	fake.extendVolumeSizeMutex.Lock()
	defer fake.extendVolumeSizeMutex.Unlock()
	fake.ExtendVolumeSizeStub = nil
	if fake.extendVolumeSizeReturnsOnCall == nil {
		fake.extendVolumeSizeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.extendVolumeSizeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeService) GetVolume(arg1 string) (*volumes.Volume, error) {
	fake.getVolumeMutex.Lock()
	ret, specificReturn := fake.getVolumeReturnsOnCall[len(fake.getVolumeArgsForCall)]
	fake.getVolumeArgsForCall = append(fake.getVolumeArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetVolumeStub
	fakeReturns := fake.getVolumeReturns
	fake.recordInvocation("GetVolume", []interface{}{arg1})
	fake.getVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeService) GetVolumeCallCount() int {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	return len(fake.getVolumeArgsForCall)
}

func (fake *FakeVolumeService) GetVolumeCalls(stub func(string) (*volumes.Volume, error)) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = stub
}

func (fake *FakeVolumeService) GetVolumeArgsForCall(i int) string {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	argsForCall := fake.getVolumeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeVolumeService) GetVolumeReturns(result1 *volumes.Volume, result2 error) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = nil
	fake.getVolumeReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) GetVolumeReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = nil
	if fake.getVolumeReturnsOnCall == nil {
		fake.getVolumeReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.getVolumeReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeStatus(arg1 string, arg2 time.Duration, arg3 string) error {
	fake.waitForVolumeToBecomeStatusMutex.Lock()
	ret, specificReturn := fake.waitForVolumeToBecomeStatusReturnsOnCall[len(fake.waitForVolumeToBecomeStatusArgsForCall)]
	fake.waitForVolumeToBecomeStatusArgsForCall = append(fake.waitForVolumeToBecomeStatusArgsForCall, struct {
		arg1 string
		arg2 time.Duration
		arg3 string
	}{arg1, arg2, arg3})
	stub := fake.WaitForVolumeToBecomeStatusStub
	fakeReturns := fake.waitForVolumeToBecomeStatusReturns
	fake.recordInvocation("WaitForVolumeToBecomeStatus", []interface{}{arg1, arg2, arg3})
	fake.waitForVolumeToBecomeStatusMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeStatusCallCount() int {
	fake.waitForVolumeToBecomeStatusMutex.RLock()
	defer fake.waitForVolumeToBecomeStatusMutex.RUnlock()
	return len(fake.waitForVolumeToBecomeStatusArgsForCall)
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeStatusCalls(stub func(string, time.Duration, string) error) {
	fake.waitForVolumeToBecomeStatusMutex.Lock()
	defer fake.waitForVolumeToBecomeStatusMutex.Unlock()
	fake.WaitForVolumeToBecomeStatusStub = stub
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeStatusArgsForCall(i int) (string, time.Duration, string) {
	fake.waitForVolumeToBecomeStatusMutex.RLock()
	defer fake.waitForVolumeToBecomeStatusMutex.RUnlock()
	argsForCall := fake.waitForVolumeToBecomeStatusArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeStatusReturns(result1 error) {
	fake.waitForVolumeToBecomeStatusMutex.Lock()
	defer fake.waitForVolumeToBecomeStatusMutex.Unlock()
	fake.WaitForVolumeToBecomeStatusStub = nil
	fake.waitForVolumeToBecomeStatusReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeService) WaitForVolumeToBecomeStatusReturnsOnCall(i int, result1 error) {
	fake.waitForVolumeToBecomeStatusMutex.Lock()
	defer fake.waitForVolumeToBecomeStatusMutex.Unlock()
	fake.WaitForVolumeToBecomeStatusStub = nil
	if fake.waitForVolumeToBecomeStatusReturnsOnCall == nil {
		fake.waitForVolumeToBecomeStatusReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.waitForVolumeToBecomeStatusReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	fake.extendVolumeSizeMutex.RLock()
	defer fake.extendVolumeSizeMutex.RUnlock()
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	fake.waitForVolumeToBecomeStatusMutex.RLock()
	defer fake.waitForVolumeToBecomeStatusMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVolumeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ volume.VolumeService = new(FakeVolumeService)
