// Code generated by counterfeiter. DO NOT EDIT.
package volumefakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/utils"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/volume"
	"github.com/gophercloud/gophercloud/openstack/blockstorage/extensions/volumeactions"
	"github.com/gophercloud/gophercloud/openstack/blockstorage/v3/volumes"
)

type FakeVolumeFacade struct {
	CreateVolumeStub        func(utils.ServiceClient, volumes.CreateOptsBuilder) (*volumes.Volume, error)
	createVolumeMutex       sync.RWMutex
	createVolumeArgsForCall []struct {
		arg1 utils.ServiceClient
		arg2 volumes.CreateOptsBuilder
	}
	createVolumeReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	createVolumeReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	DeleteVolumeStub        func(utils.RetryableServiceClient, string, volumes.DeleteOptsBuilder) error
	deleteVolumeMutex       sync.RWMutex
	deleteVolumeArgsForCall []struct {
		arg1 utils.RetryableServiceClient
		arg2 string
		arg3 volumes.DeleteOptsBuilder
	}
	deleteVolumeReturns struct {
		result1 error
	}
	deleteVolumeReturnsOnCall map[int]struct {
		result1 error
	}
	ExtendVolumeSizeStub        func(utils.ServiceClient, string, volumeactions.ExtendSizeOptsBuilder) error
	extendVolumeSizeMutex       sync.RWMutex
	extendVolumeSizeArgsForCall []struct {
		arg1 utils.ServiceClient
		arg2 string
		arg3 volumeactions.ExtendSizeOptsBuilder
	}
	extendVolumeSizeReturns struct {
		result1 error
	}
	extendVolumeSizeReturnsOnCall map[int]struct {
		result1 error
	}
	GetVolumeStub        func(utils.RetryableServiceClient, string) (*volumes.Volume, error)
	getVolumeMutex       sync.RWMutex
	getVolumeArgsForCall []struct {
		arg1 utils.RetryableServiceClient
		arg2 string
	}
	getVolumeReturns struct {
		result1 *volumes.Volume
		result2 error
	}
	getVolumeReturnsOnCall map[int]struct {
		result1 *volumes.Volume
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeVolumeFacade) CreateVolume(arg1 utils.ServiceClient, arg2 volumes.CreateOptsBuilder) (*volumes.Volume, error) {
	fake.createVolumeMutex.Lock()
	ret, specificReturn := fake.createVolumeReturnsOnCall[len(fake.createVolumeArgsForCall)]
	fake.createVolumeArgsForCall = append(fake.createVolumeArgsForCall, struct {
		arg1 utils.ServiceClient
		arg2 volumes.CreateOptsBuilder
	}{arg1, arg2})
	stub := fake.CreateVolumeStub
	fakeReturns := fake.createVolumeReturns
	fake.recordInvocation("CreateVolume", []interface{}{arg1, arg2})
	fake.createVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeFacade) CreateVolumeCallCount() int {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	return len(fake.createVolumeArgsForCall)
}

func (fake *FakeVolumeFacade) CreateVolumeCalls(stub func(utils.ServiceClient, volumes.CreateOptsBuilder) (*volumes.Volume, error)) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = stub
}

func (fake *FakeVolumeFacade) CreateVolumeArgsForCall(i int) (utils.ServiceClient, volumes.CreateOptsBuilder) {
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	argsForCall := fake.createVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeFacade) CreateVolumeReturns(result1 *volumes.Volume, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	fake.createVolumeReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) CreateVolumeReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.createVolumeMutex.Lock()
	defer fake.createVolumeMutex.Unlock()
	fake.CreateVolumeStub = nil
	if fake.createVolumeReturnsOnCall == nil {
		fake.createVolumeReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.createVolumeReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) DeleteVolume(arg1 utils.RetryableServiceClient, arg2 string, arg3 volumes.DeleteOptsBuilder) error {
	fake.deleteVolumeMutex.Lock()
	ret, specificReturn := fake.deleteVolumeReturnsOnCall[len(fake.deleteVolumeArgsForCall)]
	fake.deleteVolumeArgsForCall = append(fake.deleteVolumeArgsForCall, struct {
		arg1 utils.RetryableServiceClient
		arg2 string
		arg3 volumes.DeleteOptsBuilder
	}{arg1, arg2, arg3})
	stub := fake.DeleteVolumeStub
	fakeReturns := fake.deleteVolumeReturns
	fake.recordInvocation("DeleteVolume", []interface{}{arg1, arg2, arg3})
	fake.deleteVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeFacade) DeleteVolumeCallCount() int {
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	return len(fake.deleteVolumeArgsForCall)
}

func (fake *FakeVolumeFacade) DeleteVolumeCalls(stub func(utils.RetryableServiceClient, string, volumes.DeleteOptsBuilder) error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = stub
}

func (fake *FakeVolumeFacade) DeleteVolumeArgsForCall(i int) (utils.RetryableServiceClient, string, volumes.DeleteOptsBuilder) {
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	argsForCall := fake.deleteVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVolumeFacade) DeleteVolumeReturns(result1 error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = nil
	fake.deleteVolumeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeFacade) DeleteVolumeReturnsOnCall(i int, result1 error) {
	fake.deleteVolumeMutex.Lock()
	defer fake.deleteVolumeMutex.Unlock()
	fake.DeleteVolumeStub = nil
	if fake.deleteVolumeReturnsOnCall == nil {
		fake.deleteVolumeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVolumeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeFacade) ExtendVolumeSize(arg1 utils.ServiceClient, arg2 string, arg3 volumeactions.ExtendSizeOptsBuilder) error {
	fake.extendVolumeSizeMutex.Lock()
	ret, specificReturn := fake.extendVolumeSizeReturnsOnCall[len(fake.extendVolumeSizeArgsForCall)]
	fake.extendVolumeSizeArgsForCall = append(fake.extendVolumeSizeArgsForCall, struct {
		arg1 utils.ServiceClient
		arg2 string
		arg3 volumeactions.ExtendSizeOptsBuilder
	}{arg1, arg2, arg3})
	stub := fake.ExtendVolumeSizeStub
	fakeReturns := fake.extendVolumeSizeReturns
	fake.recordInvocation("ExtendVolumeSize", []interface{}{arg1, arg2, arg3})
	fake.extendVolumeSizeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeVolumeFacade) ExtendVolumeSizeCallCount() int {
	fake.extendVolumeSizeMutex.RLock()
	defer fake.extendVolumeSizeMutex.RUnlock()
	return len(fake.extendVolumeSizeArgsForCall)
}

func (fake *FakeVolumeFacade) ExtendVolumeSizeCalls(stub func(utils.ServiceClient, string, volumeactions.ExtendSizeOptsBuilder) error) {
	fake.extendVolumeSizeMutex.Lock()
	defer fake.extendVolumeSizeMutex.Unlock()
	fake.ExtendVolumeSizeStub = stub
}

func (fake *FakeVolumeFacade) ExtendVolumeSizeArgsForCall(i int) (utils.ServiceClient, string, volumeactions.ExtendSizeOptsBuilder) {
	fake.extendVolumeSizeMutex.RLock()
	defer fake.extendVolumeSizeMutex.RUnlock()
	argsForCall := fake.extendVolumeSizeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeVolumeFacade) ExtendVolumeSizeReturns(result1 error) {
	fake.extendVolumeSizeMutex.Lock()
	defer fake.extendVolumeSizeMutex.Unlock()
	fake.ExtendVolumeSizeStub = nil
	fake.extendVolumeSizeReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeFacade) ExtendVolumeSizeReturnsOnCall(i int, result1 error) {
	fake.extendVolumeSizeMutex.Lock()
	defer fake.extendVolumeSizeMutex.Unlock()
	fake.ExtendVolumeSizeStub = nil
	if fake.extendVolumeSizeReturnsOnCall == nil {
		fake.extendVolumeSizeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.extendVolumeSizeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeVolumeFacade) GetVolume(arg1 utils.RetryableServiceClient, arg2 string) (*volumes.Volume, error) {
	fake.getVolumeMutex.Lock()
	ret, specificReturn := fake.getVolumeReturnsOnCall[len(fake.getVolumeArgsForCall)]
	fake.getVolumeArgsForCall = append(fake.getVolumeArgsForCall, struct {
		arg1 utils.RetryableServiceClient
		arg2 string
	}{arg1, arg2})
	stub := fake.GetVolumeStub
	fakeReturns := fake.getVolumeReturns
	fake.recordInvocation("GetVolume", []interface{}{arg1, arg2})
	fake.getVolumeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeVolumeFacade) GetVolumeCallCount() int {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	return len(fake.getVolumeArgsForCall)
}

func (fake *FakeVolumeFacade) GetVolumeCalls(stub func(utils.RetryableServiceClient, string) (*volumes.Volume, error)) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = stub
}

func (fake *FakeVolumeFacade) GetVolumeArgsForCall(i int) (utils.RetryableServiceClient, string) {
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	argsForCall := fake.getVolumeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeVolumeFacade) GetVolumeReturns(result1 *volumes.Volume, result2 error) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = nil
	fake.getVolumeReturns = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) GetVolumeReturnsOnCall(i int, result1 *volumes.Volume, result2 error) {
	fake.getVolumeMutex.Lock()
	defer fake.getVolumeMutex.Unlock()
	fake.GetVolumeStub = nil
	if fake.getVolumeReturnsOnCall == nil {
		fake.getVolumeReturnsOnCall = make(map[int]struct {
			result1 *volumes.Volume
			result2 error
		})
	}
	fake.getVolumeReturnsOnCall[i] = struct {
		result1 *volumes.Volume
		result2 error
	}{result1, result2}
}

func (fake *FakeVolumeFacade) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createVolumeMutex.RLock()
	defer fake.createVolumeMutex.RUnlock()
	fake.deleteVolumeMutex.RLock()
	defer fake.deleteVolumeMutex.RUnlock()
	fake.extendVolumeSizeMutex.RLock()
	defer fake.extendVolumeSizeMutex.RUnlock()
	fake.getVolumeMutex.RLock()
	defer fake.getVolumeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeVolumeFacade) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ volume.VolumeFacade = new(FakeVolumeFacade)
