// Code generated by counterfeiter. DO NOT EDIT.
package loadbalancerfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/loadbalancer"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/properties"
	"github.com/gophercloud/gophercloud/openstack/loadbalancer/v2/pools"
)

type FakeLoadbalancerService struct {
	CreatePoolMemberStub        func(string, string, properties.LoadbalancerPool, string, int) (*pools.Member, error)
	createPoolMemberMutex       sync.RWMutex
	createPoolMemberArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 properties.LoadbalancerPool
		arg4 string
		arg5 int
	}
	createPoolMemberReturns struct {
		result1 *pools.Member
		result2 error
	}
	createPoolMemberReturnsOnCall map[int]struct {
		result1 *pools.Member
		result2 error
	}
	GetPoolIDStub        func(string) (string, error)
	getPoolIDMutex       sync.RWMutex
	getPoolIDArgsForCall []struct {
		arg1 string
	}
	getPoolIDReturns struct {
		result1 string
		result2 error
	}
	getPoolIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeLoadbalancerService) CreatePoolMember(arg1 string, arg2 string, arg3 properties.LoadbalancerPool, arg4 string, arg5 int) (*pools.Member, error) {
	fake.createPoolMemberMutex.Lock()
	ret, specificReturn := fake.createPoolMemberReturnsOnCall[len(fake.createPoolMemberArgsForCall)]
	fake.createPoolMemberArgsForCall = append(fake.createPoolMemberArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 properties.LoadbalancerPool
		arg4 string
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.CreatePoolMemberStub
	fakeReturns := fake.createPoolMemberReturns
	fake.recordInvocation("CreatePoolMember", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.createPoolMemberMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLoadbalancerService) CreatePoolMemberCallCount() int {
	fake.createPoolMemberMutex.RLock()
	defer fake.createPoolMemberMutex.RUnlock()
	return len(fake.createPoolMemberArgsForCall)
}

func (fake *FakeLoadbalancerService) CreatePoolMemberCalls(stub func(string, string, properties.LoadbalancerPool, string, int) (*pools.Member, error)) {
	fake.createPoolMemberMutex.Lock()
	defer fake.createPoolMemberMutex.Unlock()
	fake.CreatePoolMemberStub = stub
}

func (fake *FakeLoadbalancerService) CreatePoolMemberArgsForCall(i int) (string, string, properties.LoadbalancerPool, string, int) {
	fake.createPoolMemberMutex.RLock()
	defer fake.createPoolMemberMutex.RUnlock()
	argsForCall := fake.createPoolMemberArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeLoadbalancerService) CreatePoolMemberReturns(result1 *pools.Member, result2 error) {
	fake.createPoolMemberMutex.Lock()
	defer fake.createPoolMemberMutex.Unlock()
	fake.CreatePoolMemberStub = nil
	fake.createPoolMemberReturns = struct {
		result1 *pools.Member
		result2 error
	}{result1, result2}
}

func (fake *FakeLoadbalancerService) CreatePoolMemberReturnsOnCall(i int, result1 *pools.Member, result2 error) {
	fake.createPoolMemberMutex.Lock()
	defer fake.createPoolMemberMutex.Unlock()
	fake.CreatePoolMemberStub = nil
	if fake.createPoolMemberReturnsOnCall == nil {
		fake.createPoolMemberReturnsOnCall = make(map[int]struct {
			result1 *pools.Member
			result2 error
		})
	}
	fake.createPoolMemberReturnsOnCall[i] = struct {
		result1 *pools.Member
		result2 error
	}{result1, result2}
}

func (fake *FakeLoadbalancerService) GetPoolID(arg1 string) (string, error) {
	fake.getPoolIDMutex.Lock()
	ret, specificReturn := fake.getPoolIDReturnsOnCall[len(fake.getPoolIDArgsForCall)]
	fake.getPoolIDArgsForCall = append(fake.getPoolIDArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GetPoolIDStub
	fakeReturns := fake.getPoolIDReturns
	fake.recordInvocation("GetPoolID", []interface{}{arg1})
	fake.getPoolIDMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeLoadbalancerService) GetPoolIDCallCount() int {
	fake.getPoolIDMutex.RLock()
	defer fake.getPoolIDMutex.RUnlock()
	return len(fake.getPoolIDArgsForCall)
}

func (fake *FakeLoadbalancerService) GetPoolIDCalls(stub func(string) (string, error)) {
	fake.getPoolIDMutex.Lock()
	defer fake.getPoolIDMutex.Unlock()
	fake.GetPoolIDStub = stub
}

func (fake *FakeLoadbalancerService) GetPoolIDArgsForCall(i int) string {
	fake.getPoolIDMutex.RLock()
	defer fake.getPoolIDMutex.RUnlock()
	argsForCall := fake.getPoolIDArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeLoadbalancerService) GetPoolIDReturns(result1 string, result2 error) {
	fake.getPoolIDMutex.Lock()
	defer fake.getPoolIDMutex.Unlock()
	fake.GetPoolIDStub = nil
	fake.getPoolIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeLoadbalancerService) GetPoolIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.getPoolIDMutex.Lock()
	defer fake.getPoolIDMutex.Unlock()
	fake.GetPoolIDStub = nil
	if fake.getPoolIDReturnsOnCall == nil {
		fake.getPoolIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getPoolIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeLoadbalancerService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createPoolMemberMutex.RLock()
	defer fake.createPoolMemberMutex.RUnlock()
	fake.getPoolIDMutex.RLock()
	defer fake.getPoolIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeLoadbalancerService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ loadbalancer.LoadbalancerService = new(FakeLoadbalancerService)
