// Code generated by counterfeiter. DO NOT EDIT.
package vmfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/services/facades"
	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/vm"
	"github.com/gophercloud/gophercloud"
)

type FakeInstanceTypeResolver struct {
	GetInstanceTypeFlavorIDStub        func(string, *gophercloud.ServiceClient, facades.ComputeFacade) (string, error)
	getInstanceTypeFlavorIDMutex       sync.RWMutex
	getInstanceTypeFlavorIDArgsForCall []struct {
		arg1 string
		arg2 *gophercloud.ServiceClient
		arg3 facades.ComputeFacade
	}
	getInstanceTypeFlavorIDReturns struct {
		result1 string
		result2 error
	}
	getInstanceTypeFlavorIDReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeInstanceTypeResolver) GetInstanceTypeFlavorID(arg1 string, arg2 *gophercloud.ServiceClient, arg3 facades.ComputeFacade) (string, error) {
	fake.getInstanceTypeFlavorIDMutex.Lock()
	ret, specificReturn := fake.getInstanceTypeFlavorIDReturnsOnCall[len(fake.getInstanceTypeFlavorIDArgsForCall)]
	fake.getInstanceTypeFlavorIDArgsForCall = append(fake.getInstanceTypeFlavorIDArgsForCall, struct {
		arg1 string
		arg2 *gophercloud.ServiceClient
		arg3 facades.ComputeFacade
	}{arg1, arg2, arg3})
	stub := fake.GetInstanceTypeFlavorIDStub
	fakeReturns := fake.getInstanceTypeFlavorIDReturns
	fake.recordInvocation("GetInstanceTypeFlavorID", []interface{}{arg1, arg2, arg3})
	fake.getInstanceTypeFlavorIDMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeInstanceTypeResolver) GetInstanceTypeFlavorIDCallCount() int {
	fake.getInstanceTypeFlavorIDMutex.RLock()
	defer fake.getInstanceTypeFlavorIDMutex.RUnlock()
	return len(fake.getInstanceTypeFlavorIDArgsForCall)
}

func (fake *FakeInstanceTypeResolver) GetInstanceTypeFlavorIDCalls(stub func(string, *gophercloud.ServiceClient, facades.ComputeFacade) (string, error)) {
	fake.getInstanceTypeFlavorIDMutex.Lock()
	defer fake.getInstanceTypeFlavorIDMutex.Unlock()
	fake.GetInstanceTypeFlavorIDStub = stub
}

func (fake *FakeInstanceTypeResolver) GetInstanceTypeFlavorIDArgsForCall(i int) (string, *gophercloud.ServiceClient, facades.ComputeFacade) {
	fake.getInstanceTypeFlavorIDMutex.RLock()
	defer fake.getInstanceTypeFlavorIDMutex.RUnlock()
	argsForCall := fake.getInstanceTypeFlavorIDArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeInstanceTypeResolver) GetInstanceTypeFlavorIDReturns(result1 string, result2 error) {
	fake.getInstanceTypeFlavorIDMutex.Lock()
	defer fake.getInstanceTypeFlavorIDMutex.Unlock()
	fake.GetInstanceTypeFlavorIDStub = nil
	fake.getInstanceTypeFlavorIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceTypeResolver) GetInstanceTypeFlavorIDReturnsOnCall(i int, result1 string, result2 error) {
	fake.getInstanceTypeFlavorIDMutex.Lock()
	defer fake.getInstanceTypeFlavorIDMutex.Unlock()
	fake.GetInstanceTypeFlavorIDStub = nil
	if fake.getInstanceTypeFlavorIDReturnsOnCall == nil {
		fake.getInstanceTypeFlavorIDReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getInstanceTypeFlavorIDReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeInstanceTypeResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getInstanceTypeFlavorIDMutex.RLock()
	defer fake.getInstanceTypeFlavorIDMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeInstanceTypeResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vm.InstanceTypeResolver = new(FakeInstanceTypeResolver)
