// Code generated by counterfeiter. DO NOT EDIT.
package vmfakes

import (
	"sync"

	"github.com/cloudfoundry/bosh-openstack-cpi-release/src/openstack_cpi_golang/cpi/vm"
)

type FakeNetworkConfig struct {
	GetAllNetworksStub        func() []vm.Network
	getAllNetworksMutex       sync.RWMutex
	getAllNetworksArgsForCall []struct {
	}
	getAllNetworksReturns struct {
		result1 []vm.Network
	}
	getAllNetworksReturnsOnCall map[int]struct {
		result1 []vm.Network
	}
	GetDefaultNetworkStub        func() vm.Network
	getDefaultNetworkMutex       sync.RWMutex
	getDefaultNetworkArgsForCall []struct {
	}
	getDefaultNetworkReturns struct {
		result1 vm.Network
	}
	getDefaultNetworkReturnsOnCall map[int]struct {
		result1 vm.Network
	}
	GetDynamicNetworkStub        func() *vm.Network
	getDynamicNetworkMutex       sync.RWMutex
	getDynamicNetworkArgsForCall []struct {
	}
	getDynamicNetworkReturns struct {
		result1 *vm.Network
	}
	getDynamicNetworkReturnsOnCall map[int]struct {
		result1 *vm.Network
	}
	GetManualNetworksStub        func() []vm.Network
	getManualNetworksMutex       sync.RWMutex
	getManualNetworksArgsForCall []struct {
	}
	getManualNetworksReturns struct {
		result1 []vm.Network
	}
	getManualNetworksReturnsOnCall map[int]struct {
		result1 []vm.Network
	}
	GetVIPNetworkStub        func() *vm.Network
	getVIPNetworkMutex       sync.RWMutex
	getVIPNetworkArgsForCall []struct {
	}
	getVIPNetworkReturns struct {
		result1 *vm.Network
	}
	getVIPNetworkReturnsOnCall map[int]struct {
		result1 *vm.Network
	}
	SecurityGroupsStub        func() []string
	securityGroupsMutex       sync.RWMutex
	securityGroupsArgsForCall []struct {
	}
	securityGroupsReturns struct {
		result1 []string
	}
	securityGroupsReturnsOnCall map[int]struct {
		result1 []string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNetworkConfig) GetAllNetworks() []vm.Network {
	fake.getAllNetworksMutex.Lock()
	ret, specificReturn := fake.getAllNetworksReturnsOnCall[len(fake.getAllNetworksArgsForCall)]
	fake.getAllNetworksArgsForCall = append(fake.getAllNetworksArgsForCall, struct {
	}{})
	stub := fake.GetAllNetworksStub
	fakeReturns := fake.getAllNetworksReturns
	fake.recordInvocation("GetAllNetworks", []interface{}{})
	fake.getAllNetworksMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkConfig) GetAllNetworksCallCount() int {
	fake.getAllNetworksMutex.RLock()
	defer fake.getAllNetworksMutex.RUnlock()
	return len(fake.getAllNetworksArgsForCall)
}

func (fake *FakeNetworkConfig) GetAllNetworksCalls(stub func() []vm.Network) {
	fake.getAllNetworksMutex.Lock()
	defer fake.getAllNetworksMutex.Unlock()
	fake.GetAllNetworksStub = stub
}

func (fake *FakeNetworkConfig) GetAllNetworksReturns(result1 []vm.Network) {
	fake.getAllNetworksMutex.Lock()
	defer fake.getAllNetworksMutex.Unlock()
	fake.GetAllNetworksStub = nil
	fake.getAllNetworksReturns = struct {
		result1 []vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetAllNetworksReturnsOnCall(i int, result1 []vm.Network) {
	fake.getAllNetworksMutex.Lock()
	defer fake.getAllNetworksMutex.Unlock()
	fake.GetAllNetworksStub = nil
	if fake.getAllNetworksReturnsOnCall == nil {
		fake.getAllNetworksReturnsOnCall = make(map[int]struct {
			result1 []vm.Network
		})
	}
	fake.getAllNetworksReturnsOnCall[i] = struct {
		result1 []vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetDefaultNetwork() vm.Network {
	fake.getDefaultNetworkMutex.Lock()
	ret, specificReturn := fake.getDefaultNetworkReturnsOnCall[len(fake.getDefaultNetworkArgsForCall)]
	fake.getDefaultNetworkArgsForCall = append(fake.getDefaultNetworkArgsForCall, struct {
	}{})
	stub := fake.GetDefaultNetworkStub
	fakeReturns := fake.getDefaultNetworkReturns
	fake.recordInvocation("GetDefaultNetwork", []interface{}{})
	fake.getDefaultNetworkMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkConfig) GetDefaultNetworkCallCount() int {
	fake.getDefaultNetworkMutex.RLock()
	defer fake.getDefaultNetworkMutex.RUnlock()
	return len(fake.getDefaultNetworkArgsForCall)
}

func (fake *FakeNetworkConfig) GetDefaultNetworkCalls(stub func() vm.Network) {
	fake.getDefaultNetworkMutex.Lock()
	defer fake.getDefaultNetworkMutex.Unlock()
	fake.GetDefaultNetworkStub = stub
}

func (fake *FakeNetworkConfig) GetDefaultNetworkReturns(result1 vm.Network) {
	fake.getDefaultNetworkMutex.Lock()
	defer fake.getDefaultNetworkMutex.Unlock()
	fake.GetDefaultNetworkStub = nil
	fake.getDefaultNetworkReturns = struct {
		result1 vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetDefaultNetworkReturnsOnCall(i int, result1 vm.Network) {
	fake.getDefaultNetworkMutex.Lock()
	defer fake.getDefaultNetworkMutex.Unlock()
	fake.GetDefaultNetworkStub = nil
	if fake.getDefaultNetworkReturnsOnCall == nil {
		fake.getDefaultNetworkReturnsOnCall = make(map[int]struct {
			result1 vm.Network
		})
	}
	fake.getDefaultNetworkReturnsOnCall[i] = struct {
		result1 vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetDynamicNetwork() *vm.Network {
	fake.getDynamicNetworkMutex.Lock()
	ret, specificReturn := fake.getDynamicNetworkReturnsOnCall[len(fake.getDynamicNetworkArgsForCall)]
	fake.getDynamicNetworkArgsForCall = append(fake.getDynamicNetworkArgsForCall, struct {
	}{})
	stub := fake.GetDynamicNetworkStub
	fakeReturns := fake.getDynamicNetworkReturns
	fake.recordInvocation("GetDynamicNetwork", []interface{}{})
	fake.getDynamicNetworkMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkConfig) GetDynamicNetworkCallCount() int {
	fake.getDynamicNetworkMutex.RLock()
	defer fake.getDynamicNetworkMutex.RUnlock()
	return len(fake.getDynamicNetworkArgsForCall)
}

func (fake *FakeNetworkConfig) GetDynamicNetworkCalls(stub func() *vm.Network) {
	fake.getDynamicNetworkMutex.Lock()
	defer fake.getDynamicNetworkMutex.Unlock()
	fake.GetDynamicNetworkStub = stub
}

func (fake *FakeNetworkConfig) GetDynamicNetworkReturns(result1 *vm.Network) {
	fake.getDynamicNetworkMutex.Lock()
	defer fake.getDynamicNetworkMutex.Unlock()
	fake.GetDynamicNetworkStub = nil
	fake.getDynamicNetworkReturns = struct {
		result1 *vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetDynamicNetworkReturnsOnCall(i int, result1 *vm.Network) {
	fake.getDynamicNetworkMutex.Lock()
	defer fake.getDynamicNetworkMutex.Unlock()
	fake.GetDynamicNetworkStub = nil
	if fake.getDynamicNetworkReturnsOnCall == nil {
		fake.getDynamicNetworkReturnsOnCall = make(map[int]struct {
			result1 *vm.Network
		})
	}
	fake.getDynamicNetworkReturnsOnCall[i] = struct {
		result1 *vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetManualNetworks() []vm.Network {
	fake.getManualNetworksMutex.Lock()
	ret, specificReturn := fake.getManualNetworksReturnsOnCall[len(fake.getManualNetworksArgsForCall)]
	fake.getManualNetworksArgsForCall = append(fake.getManualNetworksArgsForCall, struct {
	}{})
	stub := fake.GetManualNetworksStub
	fakeReturns := fake.getManualNetworksReturns
	fake.recordInvocation("GetManualNetworks", []interface{}{})
	fake.getManualNetworksMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkConfig) GetManualNetworksCallCount() int {
	fake.getManualNetworksMutex.RLock()
	defer fake.getManualNetworksMutex.RUnlock()
	return len(fake.getManualNetworksArgsForCall)
}

func (fake *FakeNetworkConfig) GetManualNetworksCalls(stub func() []vm.Network) {
	fake.getManualNetworksMutex.Lock()
	defer fake.getManualNetworksMutex.Unlock()
	fake.GetManualNetworksStub = stub
}

func (fake *FakeNetworkConfig) GetManualNetworksReturns(result1 []vm.Network) {
	fake.getManualNetworksMutex.Lock()
	defer fake.getManualNetworksMutex.Unlock()
	fake.GetManualNetworksStub = nil
	fake.getManualNetworksReturns = struct {
		result1 []vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetManualNetworksReturnsOnCall(i int, result1 []vm.Network) {
	fake.getManualNetworksMutex.Lock()
	defer fake.getManualNetworksMutex.Unlock()
	fake.GetManualNetworksStub = nil
	if fake.getManualNetworksReturnsOnCall == nil {
		fake.getManualNetworksReturnsOnCall = make(map[int]struct {
			result1 []vm.Network
		})
	}
	fake.getManualNetworksReturnsOnCall[i] = struct {
		result1 []vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetVIPNetwork() *vm.Network {
	fake.getVIPNetworkMutex.Lock()
	ret, specificReturn := fake.getVIPNetworkReturnsOnCall[len(fake.getVIPNetworkArgsForCall)]
	fake.getVIPNetworkArgsForCall = append(fake.getVIPNetworkArgsForCall, struct {
	}{})
	stub := fake.GetVIPNetworkStub
	fakeReturns := fake.getVIPNetworkReturns
	fake.recordInvocation("GetVIPNetwork", []interface{}{})
	fake.getVIPNetworkMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkConfig) GetVIPNetworkCallCount() int {
	fake.getVIPNetworkMutex.RLock()
	defer fake.getVIPNetworkMutex.RUnlock()
	return len(fake.getVIPNetworkArgsForCall)
}

func (fake *FakeNetworkConfig) GetVIPNetworkCalls(stub func() *vm.Network) {
	fake.getVIPNetworkMutex.Lock()
	defer fake.getVIPNetworkMutex.Unlock()
	fake.GetVIPNetworkStub = stub
}

func (fake *FakeNetworkConfig) GetVIPNetworkReturns(result1 *vm.Network) {
	fake.getVIPNetworkMutex.Lock()
	defer fake.getVIPNetworkMutex.Unlock()
	fake.GetVIPNetworkStub = nil
	fake.getVIPNetworkReturns = struct {
		result1 *vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) GetVIPNetworkReturnsOnCall(i int, result1 *vm.Network) {
	fake.getVIPNetworkMutex.Lock()
	defer fake.getVIPNetworkMutex.Unlock()
	fake.GetVIPNetworkStub = nil
	if fake.getVIPNetworkReturnsOnCall == nil {
		fake.getVIPNetworkReturnsOnCall = make(map[int]struct {
			result1 *vm.Network
		})
	}
	fake.getVIPNetworkReturnsOnCall[i] = struct {
		result1 *vm.Network
	}{result1}
}

func (fake *FakeNetworkConfig) SecurityGroups() []string {
	fake.securityGroupsMutex.Lock()
	ret, specificReturn := fake.securityGroupsReturnsOnCall[len(fake.securityGroupsArgsForCall)]
	fake.securityGroupsArgsForCall = append(fake.securityGroupsArgsForCall, struct {
	}{})
	stub := fake.SecurityGroupsStub
	fakeReturns := fake.securityGroupsReturns
	fake.recordInvocation("SecurityGroups", []interface{}{})
	fake.securityGroupsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeNetworkConfig) SecurityGroupsCallCount() int {
	fake.securityGroupsMutex.RLock()
	defer fake.securityGroupsMutex.RUnlock()
	return len(fake.securityGroupsArgsForCall)
}

func (fake *FakeNetworkConfig) SecurityGroupsCalls(stub func() []string) {
	fake.securityGroupsMutex.Lock()
	defer fake.securityGroupsMutex.Unlock()
	fake.SecurityGroupsStub = stub
}

func (fake *FakeNetworkConfig) SecurityGroupsReturns(result1 []string) {
	fake.securityGroupsMutex.Lock()
	defer fake.securityGroupsMutex.Unlock()
	fake.SecurityGroupsStub = nil
	fake.securityGroupsReturns = struct {
		result1 []string
	}{result1}
}

func (fake *FakeNetworkConfig) SecurityGroupsReturnsOnCall(i int, result1 []string) {
	fake.securityGroupsMutex.Lock()
	defer fake.securityGroupsMutex.Unlock()
	fake.SecurityGroupsStub = nil
	if fake.securityGroupsReturnsOnCall == nil {
		fake.securityGroupsReturnsOnCall = make(map[int]struct {
			result1 []string
		})
	}
	fake.securityGroupsReturnsOnCall[i] = struct {
		result1 []string
	}{result1}
}

func (fake *FakeNetworkConfig) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAllNetworksMutex.RLock()
	defer fake.getAllNetworksMutex.RUnlock()
	fake.getDefaultNetworkMutex.RLock()
	defer fake.getDefaultNetworkMutex.RUnlock()
	fake.getDynamicNetworkMutex.RLock()
	defer fake.getDynamicNetworkMutex.RUnlock()
	fake.getManualNetworksMutex.RLock()
	defer fake.getManualNetworksMutex.RUnlock()
	fake.getVIPNetworkMutex.RLock()
	defer fake.getVIPNetworkMutex.RUnlock()
	fake.securityGroupsMutex.RLock()
	defer fake.securityGroupsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNetworkConfig) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ vm.NetworkConfig = new(FakeNetworkConfig)
